### PR TITLE
Merging 4.1 => 4.2

### PR DESCRIPTION
**Pull request by ayende**

### CODE REVIEW

**Comment by ppekrol** [comment]
The `SlowTests.Issues.RavenDB_12077.CanProjectSingleCollectionProperty` is failing. Did we forgot to port something or merged incorrectly?

**Comment by ppekrol** [comment]
This is probably caused by https://github.com/ravendb/ravendb/commit/8cd41e0989109fe065cd3ed251489fdd0edd5992
and https://github.com/ravendb/ravendb/blob/v4.1/src/Raven.Client/Documents/Session/Operations/QueryOperation.cs#L212-L217

Didn't have time to look more deeply there.

**Comment by ppekrol** [comment]
@ayende I've pushed more commits here + https://github.com/ravendb/ravendb/pull/7852/commits/d6a4eac9ca8f02e20f70e213c02b902f0168bc80 fixes the deserialization issue, but I'm wondering if this is correct? During deserialization we are not taking into account the modifications?

**Comment by ayende** [comment]
I'm checking into this, but some of the changes I did in `v4.2` is to the way we handle modifications.
We are no longer wiping them completely on each `ReadObject`, that might have had an impact, checking

**Comment by ayende** [comment]
Yes, it looks like that is the issue. Your fix doesn't address the actual issue (which is that `BlittableJosnReader` doesn't handle modifications properly at all).
I fixed the problem and will merge @myarichuk's changes as well and let the build server have a go at this

**Pull request merged**
