### PR TITLE
RavenDB-15176 - Backup allowed destination should be "GoogleCloud" without space

### PR DESCRIPTION
**Pull request by grisha-kotler**
https://issues.hibernatingrhinos.com/issue/RavenDB-15176

### CODE REVIEW

**Comment by ppekrol** [comment]
@ml054 @Danielle9897 @grisha-kotler Is Studio sending corrct value when Google Cloud backups is set-up?

**Comment by grisha-kotler** [comment]
Yes. `GetDestinations` is only for internal use and displaying them in the studio (view only).

**Comment by ppekrol** [comment]
What do you mean 'displaying'? We do not want to display 'GoogleCloud'.

**Comment by grisha-kotler** [comment]
Fixed

**Pull request merged**
