### PR TITLE
RavenDB-15643 - Configuration value isn't visible when using an operator certificate

### PR DESCRIPTION
**Pull request by grisha-kotler**

### CODE REVIEW

**Comment by ppekrol** [comment]
That is by design. You cannot view Server-wide value if you are not Cluster Admin, but you are aware that it is set.

**Comment by ayende** [comment]
So the question is now, why is this is a secured value?

**Comment by ppekrol** [comment]
It isn't. It is a Server-wide value and those are not visible to Operator by design.

Secured values are not visible to anyone at all times.

**Comment by grisha-kotler** [comment]
Why a user cannot view the configuration value? (not edit)

**Pull request closed without merging**
