### PR TITLE
RavenDB-12598 adding test for changes-api with aggressive caching

### PR DESCRIPTION
**Pull request by talweiss1982**

### CODE REVIEW

**Comment by ayende** [comment]
I don't understand the test. You are only testing the aggressive caching on node 1, but probably should check that reads from the other nodes are also going through and refreshing aggressive caching, no?

**Comment by talweiss1982** [comment]
The claim was that other nodes in the database group aren't getting changes when using aggressive caching. I have set aggressive caching to all 3 stores making sure each can communicate only to its original server.

**Comment by maximburyak** [comment]
@ayende the test makes sure that the changes api receives the right notifications, assuming that the aggressive caching will respond correctly. We probably should also check the behavior of the caching as well

**Comment by ayende** [comment]
You are checking this on a single store , for both the modifications and the changes.
We need to do that on different stores

**Comment by talweiss1982** [comment]
no, I'm not I'm checking on all stores, i have added the load too and test still passes.

**Review by ppekrol — APPROVED** [review]

**Comment by talweiss1982** [comment]
@ayende i have modified the test, it still  passes.

**Review by ayende — APPROVED** [review]

**Pull request merged**
