### PR TITLE
RavenDB-19309: Reproduction of error

### PR DESCRIPTION
**Pull request by redknightlois**
Includes the ability to toggle on and off (on compilation) the ability to dump the terms.

### CODE REVIEW

**Comment by redknightlois** [comment]
Incorporate fix on this PR. cc @ayende

**Comment by arekpalinski** [comment]
Multiple compact tree related tests have failed. Please check them.

**Comment by ayende** [comment]
looking into this now

**Comment by ayende** [comment]
Hm... it looks like `Bulk_Insert_Should_Throw_On_StoreAsync_Concurrent_Calls ` is a race condition that _didn't_ happen (on the github actions).

**Comment by ayende** [comment]
looking at the slow tests now

**Comment by ayende** [comment]
Okay, that was a nasty one. Hit the head against that for a while, but I think that this is a great fix, and drastically simplify both the actual scenario we had failing and any future work around that.

**Review by arekpalinski — APPROVED** [review]

**Comment by arekpalinski** [comment]
@redknightlois please review it

**Comment by redknightlois** [comment]
I got this on the SO `Questions/Search` index.

```
Fatal error. Internal CLR error. (0x80131506)
   at System.IDisposable.Dispose()
   at Voron.Data.CompactTrees.CompactTree.DefragPage(Voron.Impl.LowLevelTransaction, CursorState ByRef)
   at Voron.Data.CompactTrees.CompactTree.AddToPage(EncodedKey, Int64)
   at Corax.IndexWriter.InsertTextualField(Voron.Data.BTrees.Tree, Int32, System.Span`1<Byte>, Voron.Slice[] ByRef)
   at Corax.IndexWriter.Commit()
   at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxIndexWriteOperation.Commit(Raven.Server.Documents.Indexes.IndexingStatsScope)
   at Raven.Server.Documents.Indexes.Index.DoIndexingWork(Raven.Server.Documents.Indexes.IndexingStatsScope, System.Threading.CancellationToken)
   at Raven.Server.Documents.Indexes.Index.ExecuteIndexing()
   at Raven.Server.Documents.Indexes.Index.<StartIndexingThread>b__145_0(System.Object)
   at Raven.Server.Utils.PoolOfThreads+PooledThread.DoWork()
   at Raven.Server.Utils.PoolOfThreads+PooledThread.Run()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
```
There must be some underlying issue at the node structure from the reentrancy of `AddPage`.
This commit may be useful: `2d448772e5ea6bedb75e606cef20780aa3a29427`

**Comment by redknightlois** [comment]
More clues:
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Voron.Impl.Journal.WriteAheadJournal.PrepareToWriteToJournal(Voron.Impl.LowLevelTransaction, Voron.Impl.IPagerLevelTransactionState)
   at Voron.Impl.Journal.WriteAheadJournal.WriteToJournal(Voron.Impl.LowLevelTransaction, System.String ByRef, System.TimeSpan ByRef)
   at Voron.Impl.LowLevelTransaction.CommitStage2_WriteToJournal()
   at Voron.Impl.LowLevelTransaction.Commit()
   at Voron.Impl.Transaction.Commit()
```
So most likely we are completely whacking out a page.

**Comment by ayende** [comment]
Looking into this now

**Comment by ayende** [comment]
Great, the issue is that when we split the page, we aren't defragging the source page.
But we _assume_ that is going to be enough space to fit the new element.
In this case, we add the entry to the source page, but we aren't checking that there is enough room. At which point we basically overwrite the data with garbage and hilarity enthuse.

**Pull request merged**
