### PR TITLE
RavenDB-19176: Fixing differences in how we treat highlightings between Corax and Lucene.

### PR DESCRIPTION
**Pull request by redknightlois**
### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-19176

### Type of change
- Bug fix

### CODE REVIEW

**Comment by arekpalinski** [comment]
test this please

**Comment by arekpalinski** [comment]
@redknightlois can you please check the failing tests?

```
SlowTests.Issues.SearchHighlightings.WorkWithPostfixWildcard(options: DatabaseMode = Single , SearchEngineMode = Corax)
SlowTests.Tests.Querying.HighlightesTests.SearchWithHighlightes(options: DatabaseMode = Single , SearchEngineMode = Corax, q: "session")
SlowTests.Issues.RavenDB_6558.CanUseDifferentPreAndPostTagsPerField(options: DatabaseMode = Single , SearchEngineMode = Corax)
```

**Comment by arekpalinski** [comment]
@redknightlois did you see the test failures?

**Comment by redknightlois** [comment]
No, was working on something else and totally forgot to come back checking on the results of this one.

**Pull request merged**
