### PR TITLE
RavenDB-12364 Support Raven.Client in .net framework that uses aspnetcor

### PR DESCRIPTION
**Pull request by arekpalinski**
http://issues.hibernatingrhinos.com/issue/RavenDB-12364

### CODE REVIEW

**Comment by talweiss1982** [comment]
@arekpalinski are you sure that all requests are going through the ExecuteWithReplication method (i don't remember)?
The issue is that we might have a wrong request executor between the constructor of the AsyncServerClient and the first execute with replication since the executor is selected according to the topology.
The original issue was that we always started with replication executor and if we found out in an async manner that we are actually running as a cluster node we would switch executors midway leaving the AsyncServerClient in a faulty state where leader node was null and we expected it to be set and such errors.

**Comment by arekpalinski** [comment]
I'm not 100% sure this is a valid change. I'm waiting for tests.

All of the public methods go through `ExecuteWithReplication` and this is the only place where `RequestExecuter.ExecuteOperationAsync` is called.

**Comment by arekpalinski** [comment]
@talweiss1982 
Tests seems to be fine (I've just pushed a commit fixing one test).

As I mentioned `RequestExecuter.ExecuteOperationAsync` is called only in `ExecuteWithReplication` so I think it's enough to ensure that `UpdateTopologyAsync` is completed before calling `RequestExecuter.ExecuteOperationAsync`.

Although, please pull my changes and review the code. You have much wider view on the clustering stuff and how this change could affect it.

**Comment by talweiss1982** [comment]
@arekpalinski I have pulled your code yesterday and it looks legit.

**Comment by arekpalinski** [comment]
OK. Thank you. I'm merging it.

**Pull request merged**
