### PR TITLE
RavenDB-16338: Use sql connection from SqlAwareTestBase in SqlEtlTests

### PR DESCRIPTION
**Pull request by garayx**

### CODE REVIEW

**Comment by ppekrol** [comment]
This should be in 4.2, right?

**Comment by arekpalinski** [comment]
@garayx Can you explain what was the underlying issue?

**Comment by garayx** [comment]
> @garayx Can you explain what was the underlying issue?

`WithMsSqlDatabase` uses guid as DB name, so we can now check if the underlying issue is that the DB already exists (and modified to  SINGLE_USER) on the SQL server.

Also now we can use those tests to test the other SQL DBs we support

**Comment by arekpalinski** [comment]
OK

**Review by arekpalinski — APPROVED** [review]

**Pull request merged**
