### PR TITLE
RavenDB-5919

### PR DESCRIPTION
**Pull request by ppekrol**

### CODE REVIEW

**Comment by ayende** [comment]
This is causing test failures.

**Comment by ppekrol** [comment]
Rebased and fixed RavenDB-4110. I'm getting a lot of failures from Sparrow/Voron though.

E.g. in CaseSensitiveDeletes.ShouldWork_WithAnotherQuery
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at Voron.Data.Tables.TableValueReader.ThrowIndexOutOfRange() in C:\workspaces\HR\ravendb_3\src\Voron\Data\Tables\TableValueReader.cs:line 91
   at Voron.Data.Tables.TableValueReader.Read(Int32 index, Int32& size) in C:\workspaces\HR\ravendb_3\src\Voron\Data\Tables\TableValueReader.cs:line 55
   at Voron.Data.Tables.TableSchema.SchemaIndexDef.GetSlice(ByteStringContext context, TableValueReader& value, Slice& slice) in C:\workspaces\HR\ravendb_3\src\Voron\Data\Tables\TableSchema.cs:line 108
   at Voron.Data.Tables.Table.InsertIndexValuesFor(Int64 id, TableValueReader& value) in C:\workspaces\HR\ravendb_3\src\Voron\Data\Tables\Table.cs:line 513
   at Voron.Data.Tables.Table.Insert(TableValueBuilder builder) in C:\workspaces\HR\ravendb_3\src\Voron\Data\Tables\Table.cs:line 383
   at Raven.Server.Documents.DocumentsStorage.Put(DocumentsOperationContext context, String key, Nullable`1 expectedEtag, BlittableJsonReaderObject document, Nullable`1 lastModifiedTicks, ChangeVectorEntry[] changeVector, DocumentFlags flags) in C:\workspaces\HR\ravendb_3\src\Raven.Server\Documents\DocumentsStorage.cs:line 2158
   at Raven.Server.Documents.Handlers.BatchHandler.MergedBatchCommand.Execute(DocumentsOperationContext context) in C:\workspaces\HR\ravendb_3\src\Raven.Server\Documents\Handlers\BatchHandler.cs:line 235
   at Raven.Server.Documents.TransactionOperationsMerger.ExecutePendingOperationsInTransaction(List`1 pendingOps, DocumentsOperationContext context, Task previousOperation) in C:\workspaces\HR\ravendb_3\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 389
   at Raven.Server.Documents.TransactionOperationsMerger.MergeTransactionsOnce() in C:\workspaces\HR\ravendb_3\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 181
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Raven.Server.Documents.Handlers.BatchHandler.BulkDocs(?) in C:\workspaces\HR\ravendb_3\src\Raven.Server\Documents\Handlers\BatchHandler.cs:line 43
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Raven.Server.Routing.RequestRouter.HandlePath(?) in C:\workspaces\HR\ravendb_3\src\Raven.Server\Routing\RequestRouter.cs:line 107
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Raven.Server.RavenServerStartup.RequestHandler(?) in C:\workspaces\HR\ravendb_3\src\Raven.Server\RavenServerStartup.cs:line 114
```

This might be related to your or @redknightlois recent changes I think? I'm running all tests in R#.

**Comment by ppekrol** [comment]
Another one

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Sparrow.Collections.FastStack`1.Pop() in C:\workspaces\HR\ravendb_3\src\Sparrow\Collections\FastStack.cs:line 164
   at Voron.Data.Tables.TableSchema.Allocate(Transaction tx, TableValueBuilder& builder) in C:\workspaces\HR\ravendb_3\src\Voron\Data\Tables\TableSchema.cs:line 68
   at Voron.Data.Tables.Table.Allocate(TableValueBuilder& builder) in C:\workspaces\HR\ravendb_3\src\Voron\Data\Tables\Table.cs:line 1150
   at Raven.Server.Documents.IndexesEtagsStorage.WriteEntry(Transaction tx, String indexName, IndexEntryType type, Int32 indexIndexId, TransactionOperationContext context, Boolean isConflicted, Boolean allowOverwrite) in C:\workspaces\HR\ravendb_3\src\Raven.Server\Documents\IndexesEtagsStorage.cs:line 261
   at Raven.Server.Documents.IndexesEtagsStorage.OnIndexCreated(Index index) in C:\workspaces\HR\ravendb_3\src\Raven.Server\Documents\IndexesEtagsStorage.cs:line 121
   at Raven.Server.Documents.Indexes.IndexStore.CreateIndexInternal(Index index, Int32 indexId) in C:\workspaces\HR\ravendb_3\src\Raven.Server\Documents\Indexes\IndexStore.cs:line 266
   at Raven.Server.Documents.Indexes.IndexStore.CreateIndex(IndexDefinition definition) in C:\workspaces\HR\ravendb_3\src\Raven.Server\Documents\Indexes\IndexStore.cs:line 194
   at async Raven.Server.Documents.Handlers.IndexHandler.Put(?) in C:\workspaces\HR\ravendb_3\src\Raven.Server\Documents\Handlers\IndexHandler.cs:line 45
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Raven.Server.Routing.RequestRouter.HandlePath(?) in C:\workspaces\HR\ravendb_3\src\Raven.Server\Routing\RequestRouter.cs:line 107
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Raven.Server.RavenServerStartup.RequestHandler(?) in C:\workspaces\HR\ravendb_3\src\Raven.Server\RavenServerStartup.cs:line 114
```

**Comment by redknightlois** [comment]
Looks like. What is strange is that we haven't seen any of those for many days. Could they be race condition related?

**Comment by redknightlois** [comment]
The errors still happen?

**Comment by ayende** [comment]
Yes, the problem was that we put the cache in the `TableSchema`, but that one is shared if you have similar schemas. In indexing, this is exactly what we have, and that is causing the issue.

**Pull request merged**
