### PR TITLE
RavenDB-13542 redesigned schema upgrades

### PR DESCRIPTION
**Pull request by ppekrol**

### CODE REVIEW

**Review by arekpalinski — APPROVED** [review]

**Comment by ayende** [comment]
I'm pretty sure that we shouldn't be merging this to 4.1, _maybe_ 4.2 ?

**Comment by arekpalinski** [comment]
We need to introduce it to both 4.1 and 4.2. 

This PR is for 4.1, for 4.2 we'll need to have a separate one. Merging this PR and preparing the one for 4.2 can wait since we don't have a need to introduce any schema upgrade to 4.1

**Comment by ayende** [comment]
Di we need to merge it to 4.1? I don't think we are going to be doing much on it going forward

**Comment by arekpalinski** [comment]
Yes, we need to merge it eventually (not right now) because we need to have consistent naming of schema upgrades between any 4.x version. Once Pawel will be back we'll get back to this and decide if we want to introduce this at this point - IMO I think we're good

**Review by arekpalinski — APPROVED** [review]

**Comment by ppekrol** [comment]
Moved this to 5.0 and bumped all storages to 50_000

**Pull request merged**
