### PR TITLE
RavenDB-19746 - Simplifying defrag algorithm and reducing allocations

### PR DESCRIPTION
**Pull request by ayende**
### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-19746 

### Additional description

Simplifying & reducing allocation of defrag

### CODE REVIEW

**Comment by ppekrol** [comment]
Got:

```
Process terminated. Assertion failed.
   at Voron.Data.BTrees.RecentlyFoundTreePages.Find(Slice key) in D:\workspaces\HR\ravendb_3\src\Voron\Data\BTrees\RecentlyFoundTreePages.cs:line 103
   at Voron.Data.BTrees.Tree.TryUseRecentTransactionPage(Slice key, TreePage& page, TreeNodeHeader*& node) in D:\workspaces\HR\ravendb_3\src\Voron\Data\BTrees\Tree.cs:line 887
   at Voron.Data.BTrees.Tree.FindPageFor(Slice key, TreeNodeHeader*& node) in D:\workspaces\HR\ravendb_3\src\Voron\Data\BTrees\Tree.cs:line 646
   at Voron.Data.BTrees.Tree.DirectRead(Slice key) in D:\workspaces\HR\ravendb_3\src\Voron\Data\BTrees\Tree.cs:line 1184
   at Voron.Impl.Transaction.ReadTree(Slice treeName, RootObjectType type, Boolean isIndexTree, NewPageAllocator newPageAllocator) in D:\workspaces\HR\ravendb_3\src\Voron\Impl\Transaction.cs:line 92
   at Voron.Data.Tables.Table.CompressionDictionariesHolder.CreateCompressionDictionary(Transaction tx, Int32 id) in D:\workspaces\HR\ravendb_3\src\Voron\Data\Tables\Table.cs:line 755
   at Voron.Data.Tables.Table.CompressionDictionariesHolder.GetCompressionDictionaryFor(Transaction tx, Int32 id) in D:\workspaces\HR\ravendb_3\src\Voron\Data\Tables\Table.cs:line 745
   at Voron.Data.Tables.Table.DecompressValue(Transaction tx, Byte* ptr, Int32 size, ByteString& buffer) in D:\workspaces\HR\ravendb_3\src\Voron\Data\Tables\Table.cs:line 297
   at Voron.Data.Tables.Table.DirectReadDecompress(Int64 id, Byte* directRead, Int32& size) in D:\workspaces\HR\ravendb_3\src\Voron\Data\Tables\Table.cs:line 255
   at Voron.Data.Tables.Table.DirectRead(Int64 id, Int32& size) in D:\workspaces\HR\ravendb_3\src\Voron\Data\Tables\Table.cs:line 235
   at Voron.Data.Tables.Table.GetTableValueReader(IFixedSizeIterator it, TableValueReader& reader) in D:\workspaces\HR\ravendb_3\src\Voron\Data\Tables\Table.cs:line 1680
   at Voron.Data.Tables.Table.SeekForwardFrom(FixedSizeSchemaIndexDef index, Int64 key, Int64 skip)+MoveNext() in D:\workspaces\HR\ravendb_3\src\Voron\Data\Tables\Table.cs:line 1596
   at Raven.Server.Documents.DocumentsStorage.GetDocumentsFrom(DocumentsOperationContext context, Int64 etag, Int64 start, Int64 take, DocumentFields fields)+MoveNext() in D:\workspaces\HR\ravendb_3\src\Raven.Server\Documents\DocumentsStorage.cs:line 937
   at Raven.Server.Utils.Enumerators.PulsedTransactionEnumerator`2.MoveNext() in D:\workspaces\HR\ravendb_3\src\Raven.Server\Utils\Enumerators\PulsedTransactionEnumerator.cs:line 50
   at Raven.Server.Smuggler.Documents.DatabaseSource.GetDocumentsAsync(List`1 collectionsToExport, INewDocumentActions actions)+MoveNext() in D:\workspaces\HR\ravendb_3\src\Raven.Server\Smuggler\Documents\DatabaseSource.cs:line 183
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Raven.Server.Smuggler.Documents.DatabaseSource.GetDocumentsAsync(List`1 collectionsToExport, INewDocumentActions actions)+System.Collections.Generic.IAsyncEnumerator<Raven.Server.Smuggler.Documents.DocumentItem>.MoveNextAsync()
   at Raven.Server.Smuggler.Documents.DatabaseSmuggler.ProcessDocumentsAsync(SmugglerResult result, BuildVersionType buildType) in D:\workspaces\HR\ravendb_3\src\Raven.Server\Smuggler\Documents\DatabaseSmuggler.cs:line 686
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder.SetResult()
   at Raven.Server.Smuggler.Documents.StreamDestination.StreamDocumentActions.WriteDocumentAsync(DocumentItem item, CountsWithLastEtagAndAttachments progress) in D:\workspaces\HR\ravendb_3\src\Raven.Server\Smuggler\Documents\StreamDestination.cs:line 1128
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder.SetResult()
   at Raven.Server.Smuggler.Documents.StreamDestination.StreamDocumentActions.WriteUniqueAttachmentStreamsAsync(Document document, CountsWithLastEtagAndAttachments progress) in D:\workspaces\HR\ravendb_3\src\Raven.Server\Smuggler\Documents\StreamDestination.cs:line 1235
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder.SetResult()
   at Raven.Server.Smuggler.Documents.StreamDestination.StreamDocumentActions.WriteAttachmentStreamAsync(LazyStringValue hash, Stream stream, String tag) in D:\workspaces\HR\ravendb_3\src\Raven.Server\Smuggler\Documents\StreamDestination.cs:line 1276
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder.SetResult()
   at Sparrow.Json.AsyncBlittableJsonTextWriter.WriteStreamAsync(Stream stream, CancellationToken token) in D:\workspaces\HR\ravendb_3\src\Sparrow\Json\AsyncBlittableJsonTextWriter.cs:line 30
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.IO.Stream.<ReadAsync>g__FinishReadAsync|42_0(Task`1 readTask, Byte[] localBuffer, Memory`1 localDestination)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by ayende** [comment]
How did you get this error? I tried running the tests and I'm not seeing that.

**Comment by ayende** [comment]
Note that tests failed, and I fixed this, should be simpler / easier to follow now

**Comment by arekpalinski** [comment]
> How did you get this error? I tried running the tests and I'm not seeing that.

Pawel got it with the usage of  the sample data set which reproduced this memory issue during the backup.

**Comment by arekpalinski** [comment]
I run the tests again since we got `The active test run was aborted. Reason: Test host process crashed`

**Comment by arekpalinski** [comment]
Run the tests few times already on Jenkins - no crash

**Comment by ayende** [comment]
Will look into both of those, thanks. 
I hoped that the index fix would resolve it, looks like might need more work

**Comment by ayende** [comment]
I run the tests locally a few time. Created a sample database and indexes in release and debug mode.
I can't get it to fail.
I'm worried about the failure in https://github.com/ravendb/ravendb/pull/15562 as well, given that those are separate changes, but both crashing the process?

**Comment by arekpalinski** [comment]
I think the crash here could not be related to your changes. Something transient.

https://jenkins.hibernatingrhinos.com/job/PR_Tests/4841/consoleFull

**Comment by ayende** [comment]
Okay, thanks.

**Comment by arekpalinski** [comment]
Yeah, more test builds look fine:

https://jenkins.hibernatingrhinos.com/job/PR_Tests/4852/
https://jenkins.hibernatingrhinos.com/job/PR_Tests/4850/
https://jenkins.hibernatingrhinos.com/job/PR_Tests/4851/

Edit: ~~Still there is the crash which Pawel reproduced with sample data~~ Still need to validate the fix using the sample data where Pawel got the assertion failure

**Comment by ayende** [comment]
Pretty sure that the fix is here: https://github.com/ravendb/ravendb/pull/15617/commits/dab0cd69df50cf91ecefb63685b718f2a7b03ea9

Wasn't able to reproduce something there.

**Pull request merged**
