### PR TITLE
RavenDB-12744 A resolved document must preserve the original change v…

### PR DESCRIPTION
**Pull request by karmeli87**
…ector to avoid ping-pong replication

but it must update the global change vector.

### CODE REVIEW

**Review by ppekrol — APPROVED** [review]

**Comment by ppekrol** [comment]
@karmeli87 Can you check the failing test?

**Comment by karmeli87** [comment]
Already fixed here https://github.com/ravendb/ravendb/pull/8558

**Comment by ppekrol** [comment]
I've rebased the PR. Let's do another CI round.

**Comment by ayende** [comment]
I'm not sure that I'm following, the merged change vector for the conflict is the merged vectors of the documents, which should end up the same on all nodes, no?

**Comment by karmeli87** [comment]
Yes, the problem was that, that merged change vector was set as the global change vector. Instead we need to merge it into the global one.

**Pull request merged**
