### PR TITLE
RavenDB-23081: Remove redundant work.

### PR DESCRIPTION
**Pull request by redknightlois**
### Issue link
https://issues.hibernatingrhinos.com/issue/RavenDB-23081

### Additional description

Redundant Voron code harms more Corax than Lucene. Improvements to it will impact both but it would provide more improvements to Corax.

### Type of change

- [ ] Bug fix
- [ ] Regression bug fix
- [x] Optimization
- [ ] New feature

### How risky is the change?

- [x] Low 
- [ ] Moderate 
- [ ] High
- [ ] Not relevant

### Backward compatibility

- [x] Non breaking change
- [ ] Ensured. Please explain how has it been implemented?
- [ ] Breaking change
- [ ] Not relevant

### Is it platform specific issue?

- [ ] Yes. Please list the affected platforms.
- [x] No

### Documentation update

- [ ] This change requires a documentation update. Please mark the issue on YouTrack using `Documentation Required` tag.
- [x] No documentation update is needed 

### Testing by Contributor

- [x] Tests have been added that prove the fix is effective or that the feature works
- [ ] Internal classes added to the test class (e.g. entity or index definition classes) have the lowest possible access modifier (preferable `private`) 
- [ ] It has been verified by manual testing

### Testing by RavenDB QA team

- [x] This change requires a special QA testing due to possible performance or resources usage implications (CPU, memory, IO). Please mark the issue on YouTrack using `QA Required` tag.
- [ ] No special testing by RavenDB QA team is needed

### Is there any existing behavior change of other features due to this change?

- [ ] Yes. Please list the affected features/subsystems and provide appropriate explanation
- [x] No

### UI work

- [ ] It requires further work in the Studio. Please mark the issue on YouTrack using `Studio Required` tag.
- [x] No UI work is needed

### CODE REVIEW

**Review by ayende — APPROVED** [review]

**Comment by arekpalinski** [comment]
> How risky is the change?
> - [x] Low

Why not targeting it to 6.0 then? We already have many Corax users which might potentially benefit from it.

> - [x] No special testing by RavenDB QA team is needed

Shouldn't we confirm that this makes an improvement? Using the scenarios where the issue has been spotted.

**Comment by arekpalinski** [comment]
Tests are still waiting in the queue - https://jenkins.hibernatingrhinos.com/job/PR_Tests/12824/

**Comment by redknightlois** [comment]
Because it is not ready and started the PR for v7.0. But when it is done (all tests pass) I will rebase this for v6.0 too and we will be able to test them.

**Comment by redknightlois** [comment]
Superseded by https://github.com/ravendb/ravendb/pull/19651

**Pull request closed without merging**
