### PR TITLE
RavenDB-18511 Improve setup wizard with BYO certificate that doesn't …

### PR DESCRIPTION
**Pull request by ayende**
…match our expectations

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-18511 

### Additional description

Support certificates in the wizard that:

* don't have a subject
* don't use a wildcard
* don't have a., b., c. prefixes

### Type of change

- Bug fix

### How risky is the change?

- Moderate 

### Backward compatibility

- Non breaking change

### Is it platform specific issue?

- No

### Documentation update

- No documentation update is needed 

### Testing 

- It has been verified by manual testing

### Is there any existing behavior change of other features due to this change?

- No

### UI work

- No UI work is needed

### CODE REVIEW

**Comment by ml054** [comment]
Should we care about this: https://frasertweedale.github.io/blog-redhat/posts/2017-07-11-cn-deprecation.html ?

CN for domain name is deprecated, we should use dns names extension in certs (SAN). Should we start warning about that?

**Comment by ayende** [comment]
That is what this code is doing, mind. But there is no point in warning.
You'll typically have the domain both the the Name and SAN Fields.

**Comment by ml054** [comment]
Ok I thought about warning since this is BYO flow.

**Review by ml054 — APPROVED** [review]

**Comment by gregolsky** [comment]
@omerlewitz WRT `rvn create-package` do we use `SetupManager.cs` there too or these changes need to be applied somewhere else?

How is it going to work with our split to RootDomain and Domain in the setup parameters json file?

**Review by omerlewitz — APPROVED** [review]

**Review by omerlewitz — APPROVED** [review]

**Comment by omerlewitz** [comment]
@gregolsky it will just be to be applied in `5.2` so I will resolve the conflict and that's about it.

**Review by gregolsky — APPROVED** [review]

**Pull request merged**
