### PR TITLE
fix for RavenDB-12165

### PR DESCRIPTION
**Pull request by myarichuk**

### CODE REVIEW

**Comment by ppekrol** [comment]
@myarichuk can you submit this PR without commits from previous ones?

**Comment by myarichuk** [comment]
Made changes to test file structure here : https://github.com/ravendb/ravendb/pull/7869/commits/1c3afb776967373b3a64d80b3503a867d08023c4
I can, but it will be additional work on restructuring and resubmitting the PRs, because I continued working on changed test classes. 
Do you prefer I would do those?

**Comment by myarichuk** [comment]
Note that the initial PR today - https://github.com/ravendb/ravendb/pull/7867 - it has the test changes. In order to resubmit those PRs, I will probably merge the following PRs into one 
First - https://github.com/ravendb/ravendb/pull/7867
Second - https://github.com/ravendb/ravendb/pull/7868
And then this PR

**Comment by ppekrol** [comment]
If new commits require code from other PRs then it is better to push new commits to the initial PR, than opening a new one.

**Comment by ayende** [comment]
Closing this PR, please use https://github.com/ravendb/ravendb/pull/7880 as your baseline.
Probably by the time you'll see this it will already be merged, so just cherry-pick a new RP / rebase.

**Pull request closed without merging**
