### PR TITLE
RavenDB-5203: Add gzip and caching for static resources and prepare f…

### PR DESCRIPTION
**Pull request by jbayardo**
…or migration of APIs to gzip

Please review. This is not particularly great in terms of the development cycle (loading 300 files into the cache and compressing them takes some amount of time), but I have been seeing a lot of speed up over the network.

I will add measurements to the tracker tomorrow.

### CODE REVIEW

**Comment by ayende** [comment]
@Danielle9897 Please test this

**Comment by gregolsky** [comment]
While testing please pay attention to these `charset=utf-8` additions in Release mode (when built with `build.ps1`). They thrown somewhere around `new MediaTypeHeaderValue...`, can't recall the exact place at the moment.

**Comment by jbayardo** [comment]
@gregolsky I fixed that. It was within the Zip file serving originally. Did you find any other place where it throws?. It is worth noticing that adding the charset is the only way to stop browsers from complaining that files don't have some encoding.

Aside from that, it should be noted that the implementation is expected to work with files being changed while it is running (even if the zip file is changed). If you are actually using that as part of the development cycle, I would be grateful if you could try it; I did some testing today, but it would be good to have some more.

**Comment by Danielle9897** [comment]
1. Loading & refreshing times seem quite fine
2. But - changes done to *.ts / *.html files (from vs) are Not seen in the browser when refreshing

**Comment by jbayardo** [comment]
This should now be working for all requests. In the particular case of studio files, cache invalidation seems to work correctly.

**Comment by Danielle9897** [comment]
1.  Loading times are good - as before
2.  We are good with changes done to *.html -BUT- changes done in *.ts are NOT reflected

**Comment by ayende** [comment]
Merged in #3654

**Pull request closed without merging**
