### PR TITLE
RavenDB-17599: Preparation of the test infrastructure

### PR DESCRIPTION
**Pull request by redknightlois**
This PR prepares the testing infrastructure to be able to use seamlessly Corax and Lucene when porting test theories. 

PR is separated because it can be pushed independently from the main work-item.

### CODE REVIEW

**Comment by redknightlois** [comment]
@ppekrol Do we have a way to automatically fix tabs? Because I have everything properly setup on VS but somehow I cannot fix this file but doesn't show either where the tab is.

**Comment by ppekrol** [comment]
Try maybe in Notepad++ ? View -> Show Symbols -> Tabs ? There is also Edit -> Blank Operations -> Tab to Space

**Comment by ppekrol** [comment]
Fixed

**Comment by ppekrol** [comment]
Ignore that, I will check later what is going on.

**Comment by redknightlois** [comment]
I though that the issue may be that you cannot have any commit, but after pushing a single squashed commit there was no change. 

I am leaning on something on the Powershell itself, because those 3 files do not show up when I do File Search on Notepad++.

**Comment by arekpalinski** [comment]
@redknightlois 

We need to take a bit different approach in dealing with test cases for Corax / Lucene. Eventually the corax branch will be merged to 6.0 where we'll have sharding. Some of the tests will need to run on Lucene / Corax and sharded / non-sharded db - so 4 cases per a single test.

We're gonna introduce a new attribute `RavenDataAttribute` and use it instead of `SearchEngineClassData` that we have right now. You can see it in the unmerged PR to sharding branch - note that the part for corax is commented:

https://github.com/ravendb/ravendb/pull/13531/files#diff-ef8dfde87253ae4ce7ffc027320d709f67c8e2eb386961129594f62093881b00

We didn't manage to replace the current attribute to `RavenDataAttribute`. Would you like to handle it as part of this PR?

**Comment by arekpalinski** [comment]
Also you could check the warnings in [src/Voron/Data/Sets/SetLeafPage.cs](https://github.com/ravendb/ravendb/pull/13761/files#diff-dc6411625f71d7e4c2909424a8beb3787f5a4874aea261d0254e2c92a866b873). In particular there are some about Unrechable code detected

**Comment by redknightlois** [comment]
@arekpalinski I wouldnt dare to touch yet those... because in truth I am not entirely sure why it ended up like that. If you look at it, there are certain 'strange' features on it. Not for this PR by all means. Regarding the `RavenDataAttribute` we have an issue there which is that `Sharding` and `Corax` are been developed in parallel. Certainly, the last to come will have to do the changes on the main, but I don't see a proper way to handle it without merging the two branches properly OR building something that could be applied to 5.2 branch that would do nothing on the main branch and each branch can 'specialize' upon. 

What do you think?

**Comment by redknightlois** [comment]
I have been prototyping it, and while I am having a few issues here and there (things I want to have working on a very particular way and XUnit is not helping) it is totally doable to make a 2 steps PR. Working on it.

**Comment by redknightlois** [comment]
Superseded by https://github.com/ravendb/ravendb/pull/13779

**Pull request closed without merging**
