### PR TITLE
[RavenDB-13501] check for delete changes last, to override any other changes.(whatchanged)

### PR DESCRIPTION
**Pull request by Or-Geva**

### CODE REVIEW

**Comment by Or-Geva** [comment]
https://issues.hibernatingrhinos.com/issue/RavenDB-13501

**Comment by Postyy** [comment]
https://issues.hibernatingrhinos.com/issue/RavenDB-13501

**Comment by ayende** [comment]
Do we want to make this change in 3.5?

**Comment by ppekrol** [comment]
It originated from 3.5 thread on google groups.

**Pull request merged**
