### PR TITLE
RavenDB-5664 added JavaScriptParseException, fixed hanging WillLog test

### PR DESCRIPTION
**Pull request by ppekrol**

### CODE REVIEW

**Comment by ayende** [comment]
what caused WillLog to hang?

**Comment by ppekrol** [comment]
I've accidentally merged both the exceptions into one so we never got here: https://github.com/ravendb/ravendb/blob/v4.0/src/Raven.Server/Documents/SqlReplication/SqlReplication.cs#L243-L248
And this test expects to get a log message from that part.

**Comment by ayende** [comment]
We should change the test to have a timeout

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ppekrol** [comment]
Done

**Pull request merged**
