### PR TITLE
RavenDB-7263: CompareInfo m_sortHandle was renamed to _sortHandle. So…

### PR DESCRIPTION
**Pull request by aviviadi**
…lves related tests

### CODE REVIEW

**Comment by ayende** [comment]
Why didn't it fail on Windows, then?

**Comment by aviviadi** [comment]
@ayende No. This is linux only problem (from quick reading this: https://github.com/dotnet/coreclr/issues/4784)
The win call to GetCollationKeyWin32 uses win32 native api so it is not related to there

**Comment by ayende** [comment]
So you change would make it work on Linux, but break Winodws?

**Comment by aviviadi** [comment]
@ayende No. My change is posix only change : https://github.com/ravendb/ravendb/blob/v4.0/src/Raven.Server/Documents/Indexes/Persistence/Lucene/Collation/CollationKeyFilter.cs#L117

Windows uses : https://github.com/ravendb/ravendb/blob/v4.0/src/Raven.Server/Documents/Indexes/Persistence/Lucene/Collation/CollationKeyFilter.cs#L53

**Pull request merged**
