### PR TITLE
RavenDB-11166 Support include for subscriptions

### PR DESCRIPTION
**Pull request by ayende**

### CODE REVIEW

**Review by ppekrol — APPROVED** [review]

**Comment by ppekrol** [comment]
@maximburyak Can you check this?

**Comment by maximburyak** [comment]
Looks good, but it lacks generic API

**Comment by ppekrol** [comment]
Can you create an issue for that?

**Comment by maximburyak** [comment]
sure http://issues.hibernatingrhinos.com/issue/RDBC-206

**Pull request merged**
