### PR TITLE
RavenDB-7598 Decide which libsodium to use in runtime; output it to p…

### PR DESCRIPTION
**Pull request by gregolsky**
…ackage

### CODE REVIEW

**Comment by ayende** [comment]
@gregolsky See https://github.com/dotnet/coreclr/issues/12103

Would it make more sense to use it via `#if` ? How messy would that make our nuget deployment?

**Comment by gregolsky** [comment]
We want our package to be runnable on all platforms. It's not like server, it's one for them all, so we need to figure out which one we'd like to use at runtime. 

I first thought if we could somehow subclass DllImportAttribute, but it's sealed, so we're left with this messy solution.

We took Grpc.Core as an example for packing. For what it's worth they use delegates to invoke native methods https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/Internal/NativeMethods.cs , but @arekpalinski pointed out we probably don't want that.

**Comment by ayende** [comment]
Yeah, the conditions are always going to eval the same, so the branch predictor will be better then doing a jump

**Comment by gregolsky** [comment]
What do you mean by branch predictor?

**Comment by ayende** [comment]
See https://en.wikipedia.org/wiki/Branch_predictor

If we always go a certain way in a conditional, the CPU will optimize it.

**Pull request merged**
