### PR TITLE
RavenDB-12474 update supported browser detection

### PR DESCRIPTION
**Pull request by ml054**

### CODE REVIEW

**Review by ayende — COMMENTED** [review]
We need this on 4.0 as well, no?

**Comment by ml054** [comment]
Yes, thanks. Will create PR in few seconds.

**Comment by ayende** [comment]
Also, what about chormenium?

**Comment by ml054** [comment]
What's chormenium ?

**Comment by arekpalinski** [comment]
https://www.chromium.org/Home ?

**Comment by ml054** [comment]
check returns true for chromium, but since chrome is based on chromium, both browsers are supported by us.

**Pull request merged**
