### PR TITLE
RavenDB-12005: LazyStringValue LastIndexOf and LastIndexOfAny bug fix…

### PR DESCRIPTION
**Pull request by maximburyak**
…es and general implementation improvement

### CODE REVIEW

**Comment by maximburyak** [comment]
Do Not Merge

**Comment by ppekrol** [comment]
@maximburyak Hmm, I've just merged another PR with a fix for this only. Can you check those conflicting lines?

**Comment by maximburyak** [comment]
@ppekrol yeah, there's more to it then the specific fix (crushing tests as it seems) I'll be looking at it at slower pace (you've fixed the specific issue in your PR)

**Comment by ppekrol** [comment]
I'm closing this down. Please reopen when needed.

**Pull request closed without merging**
