### PR TITLE
RavenDB-12015 - remove StoreNextMapResultId from the dispose method

### PR DESCRIPTION
**Pull request by grisha-kotler**

### CODE REVIEW

**Comment by ppekrol** [comment]
@grisha-kotler I think that you wanted to send this to v4.0?

**Comment by ppekrol** [comment]
I will handle that.

**Comment by grisha-kotler** [comment]
It's for both 4.0 and 4.1

**Comment by grisha-kotler** [comment]
Creating another PR :)

**Comment by ppekrol** [comment]
https://github.com/ravendb/ravendb/pull/8287

**Pull request closed without merging**
