### PR TITLE
Install sourcelink

### PR DESCRIPTION
**Pull request by PieterjanDeClippel**
### Issue link

No issue

### Additional description

Installs sourcelink into the class libraries, which enables users to step into this code while debugging.

### Type of change

- [ ] Bug fix
- [ ] Regression bug fix
- [x] Optimization
- [ ] New feature

### How risky is the change?

- [x] Low 
- [ ] Moderate 
- [ ] High
- [ ] Not relevant

### Backward compatibility

- [x] Non breaking change
- [ ] Ensured. Please explain how has it been implemented?
- [ ] Breaking change
- [ ] Not relevant

### Is it platform specific issue?

- [ ] Yes. Please list the affected platforms.
- [x] No

### Documentation update

- [ ] This change requires a documentation update. Please mark the issue on YouTrack using `Documentation Required` tag.
- [x] No documentation update is needed 

### Testing by Contributor

- [ ] Tests have been added that prove the fix is effective or that the feature works
- [ ] Internal classes added to the test class (e.g. entity or index definition classes) have the lowest possible access modifier (preferable `private`) 
- [x] It has been verified by manual testing

### Testing by RavenDB QA team

- [ ] This change requires a special QA testing due to possible performance or resources usage implications (CPU, memory, IO). Please mark the issue on YouTrack using `QA Required` tag.
- [x] No special testing by RavenDB QA team is needed

### Is there any existing behavior change of other features due to this change?

- [ ] Yes. Please list the affected features/subsystems and provide appropriate explanation
- [x] No

### UI work

- [ ] It requires further work in the Studio. Please mark the issue on YouTrack using `Studio Required` tag.
- [x] No UI work is needed

### CODE REVIEW

**Comment by ppekrol** [comment]
Thank you @PieterjanDeClippel for contribution! How does sourcelink work now starting from .NET 8? We also do have a very old package installed called 'SourceLink.Create.CommandLine' and I'm wondering if we should not uninstall it now (we are using it in buildProjects.ps1 file). The whole build process can be run from the root directory via `build.ps1` file.

**Comment by PieterjanDeClippel** [comment]
Hi, thanks for looking into this.

I think indeed that the other package (`SourceLink.Create.CommandLine`) can be removed from the project.
When `Microsoft.SourceLink.Github` is installed in a class-library, `dotnet build` adds a `<repository>` tag to the package nuspec file, containing the repository specified in the csproj file, which contains the repostiroy url and commit sha-checksum from which the package was built (I think during CI/CD).

Visual Studio reads this tag from the nuspec and downloads the sources (even for private repositories which your user has access to).

So all someone needs to do is install the package in class libraries.

([See this comment from pinkfloydx33](https://stackoverflow.com/questions/66893338/packagereference-to-project-in-the-same-solution-git-repository#comment118250137_66893338))

**Comment by PieterjanDeClippel** [comment]
@ppekrol Apparently starting from .NET 8, SourceLink is included in the .NET SDK - and there's no need to add the NuGet package anymore, it all happens by default. Closing

**Comment by ppekrol** [comment]
That is very interesting, didn't know that. More info is [here](https://github.com/dotnet/sourcelink?tab=readme-ov-file#using-source-link-in-net-projects). Thanks for looking into that @PieterjanDeClippel

**Pull request closed without merging**
