### PR TITLE
RavenDB-5435 reducing compression.buffers and scratch files on idle

### PR DESCRIPTION
**Pull request by ppekrol**

### CODE REVIEW

**Comment by ayende** [comment]
We are already controlling the size of the compression buffer here:
https://github.com/ayende/ravendb/blob/v4.0/src/Voron/Impl/Journal/WriteAheadJournal.cs#L1055

So it will reduce to the max scratch file size, but if we have nothing to do, we might get rid of everything as well.

I wonder if we can also get rid of the existing scratch file (which will likely be large)

**Comment by ppekrol** [comment]
This is what I was thinking. First trim will be to 256 MB if greater and if we have nothing to do then reduce to 64KB.

**Comment by ppekrol** [comment]
Not sure about scratch. We would have to prevent read transactions (queries) and apply logs to data file in meanwhile. Also I think that txw Id should be increased.

**Comment by ayende** [comment]
Yeah, let us ignore this for now, it is going to be 256MB after pretty big writes.

**Pull request merged**
