### PR TITLE
RavenDB-13953 Allow to define document id postfix in RavenDB ETL

### PR DESCRIPTION
**Pull request by ayende**
### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-13953 

### Additional description

We can now define a `DocumentIdPostfix` in the ETL process.
That would ensure that you can send remotes from two ETLs on different machines who share the same id space without conflicts.

### Type of change

- New feature

### How risky is the change?

- Low 

### Backward compatibility

- Non breaking change

### Is it platform specific issue?

- No

### Documentation update

- This change requires a documentation update. Please mark the issue on YouTrack using `Documentation Required` tag.

### Testing 

- Tests have been added that prove the fix is effective or that the feature works

### Is there any existing behavior change of other features due to this change?

- No

### UI work

- It requires further work in the Studio

### CODE REVIEW

**Comment by ayende** [comment]
Looks like this requires code change in Studio to just compile the studio :-(. Leaving this for now until proper studio work can be done.

**Review by arekpalinski — COMMENTED** [review]
1. The test added here has failed.
2. What is the real case scenario where users will benefit from that functionality?

**Comment by ayende** [comment]
Assume that you have 3 RavenDB servers, completely isolated from one another.
You want to setup ETL from them to a shared source.
You now need to face a problem, the have the same ids, but different (`users/1-A` exists on all).

This allows you to carve out space for this.

**Comment by arekpalinski** [comment]
Thanks. That will be helpful info when for documentation purposes as well I think.

**Comment by ayende** [comment]
This is *really* strange, because it does pass on my end. 
Pushing a rebased version,we'll see how that works

**Review by arekpalinski — APPROVED** [review]

**Pull request merged**
