### PR TITLE
RavenDB-5919 : Indexes(WIP)- remove IndexToAdd and change index endPoint …

### PR DESCRIPTION
**Pull request by efratshenhar**
…to one endPoint

### CODE REVIEW

**Comment by ppekrol** [comment]
PutIndexOperation should stay, it should send array with 1 element

**Comment by ayende** [comment]
Why?
We just add a `params` there.

**Comment by ayende** [comment]
`store.Admin.Send(new PutIndexesOperation(indexDefinition));`

**Comment by ppekrol** [comment]
params is fine also, true.
Needs to be added and tests simplified.

Was thinking more about the API, with params you will get the array as result requiring you to do:
var indexId = store.Admin.Send(new PutIndexesOperation(indexDefinition))[0];
And in my option it would be unwrapped by the operation itself:
var indexId = store.Admin.Send(new PutIndexOperation(indexDefinition));

**Comment by ayende** [comment]
This is our lower level API, not really something users will call directly. They use `IndexCreation` for that, no?

**Comment by ppekrol** [comment]
ok, so let's stay with params.

**Pull request merged**
