### PR TITLE
RavenDB-17024 Add support for arm64 Docker image in build scripts 

### PR DESCRIPTION
**Pull request by poissoncorp**
https://issues.hibernatingrhinos.com/issue/RavenDB-17024

### CODE REVIEW

**Comment by gregolsky** [comment]
Addresses #12531

**Comment by gregolsky** [comment]
@poissoncorp I believe we need to add `Dockerfile.arm64v8` file and use it

**Comment by gregolsky** [comment]
Can you rebase it to `v4.2`? We got ARM support there too.

**Review by gregolsky — APPROVED** [review]

**Review by gregolsky — CHANGES_REQUESTED** [review]
https://github.com/ravendb/ravendb/pull/12682#issuecomment-902650590

**Comment by poissoncorp** [comment]
https://github.com/ravendb/ravendb/pull/12686 v4.2

**Review by gregolsky — APPROVED** [review]

**Comment by gregolsky** [comment]
@poissoncorp and the conflicts, can you resolve them?

**Pull request closed without merging**
