### PR TITLE
RavenDB-6835

### PR DESCRIPTION
**Pull request by arekpalinski**

### CODE REVIEW

**Comment by ayende** [comment]
What is the behavior now for PatchByIndex if a document was update midway through?

**Comment by arekpalinski** [comment]
The current behavior of `PatchByIndex` is that first we collect ids of docs which we need to patch then we patch docs in a write transaction (in batches, `const int BatchSize = 1024`) and _don't_ specify the expected etag, so we don't care about the updates done meanwhile.

Here (patch by collection, delete by collection) I changed that behavior so we get the concurrency exception if a doc has changed meanwhile and thought about making the same change for `PatchByIndex / DeleteByIndex`.

Will it be fine or should I leave it as is and ignore the concurrency?

**Comment by ayende** [comment]
Yes, it is fine to ignore the concurrency, but we need to document it.

**Comment by arekpalinski** [comment]
OK

**Pull request merged**
