### PR TITLE
[4.0] Raven db 10770 (Jint concurrency issue)

### PR DESCRIPTION
**Pull request by maximburyak**

### CODE REVIEW

**Comment by lahma** [comment]
Can someone trigger new nightly build so I can test this? Issue tracker is down so can't comment there.

**Comment by ppekrol** [comment]
@lahma We are moving our internal machines to newer and faster drives. Nightly should be out within an hour.

**Comment by ppekrol** [comment]
@lahma Nightly released.

**Comment by lahma** [comment]
Thank you, got the server already now waiting for MyGet to return online to get the client.

**Pull request merged**
