### PR TITLE
RavenDB-12318 Add includes to graph queries

### PR DESCRIPTION
**Pull request by talweiss1982**

### CODE REVIEW

**Review by ayende — APPROVED** [review]

**Comment by ml054** [comment]
@talweiss1982 Did you test studio part? If not I can do this.

**Comment by talweiss1982** [comment]
@ml054 I'm not sure what you mean by test the studio part, i have ran include queries manually to test that it works and added a test.

**Comment by ayende** [comment]
image

**Comment by ml054** [comment]
I just wanted to confirm that includes tab was shown.

**Pull request merged**
