### PR TITLE
RavenDB-10028 Moving to custom xunit (from the xunit/master) build du…

### PR DESCRIPTION
**Pull request by talweiss1982**
…e to an issue with assembly resolving

### CODE REVIEW

**Comment by ppekrol** [comment]
Is there a possibility to integrate this with official xunit? Having a custom one in a long run could be problematic to maintain.

**Comment by ayende** [comment]
This is their code, but it isn't released yet.
We'll be moving back to the mainlike as soon as they make a release

**Comment by ppekrol** [comment]
Great, we can move to myget https://myget.org/feed/xunit/package/nuget/xunit ?

**Comment by ayende** [comment]
@talweiss1982 Can you check?

**Comment by talweiss1982** [comment]
I have tested this version too and it also have the same issue as 2.3.1 :(
I'll open an issue to undo this in the future.
http://issues.hibernatingrhinos.com/issue/RavenDB-10061

**Pull request merged**
