### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by DamirAinullin**
Fixes of  some minor bugs

### CODE REVIEW

**Comment by ayende** [comment]
Hi,
We don't accept any more changes to the 3.0 branch that aren't major bug fixes.
Please send a PR to the 3.5 branch.

Also, we won't accept "small fixes", please separate the changes to individual commits with explanation on what you are doing and why.

See the contrib guide:
http://ravendb.net/contributing

**Comment by DamirAinullin** [comment]
@ayende Hi, thank you for response. I will send PR to 3.5.
I want to make changes by one commit because it is just warnings/errors of static analyzer.
Do you accept it if I will make it by one commit? I can change commt message if you want.

**Comment by ayende** [comment]
What static analyzer ? 
And one commit is not good if there are different things going on there

**Comment by DamirAinullin** [comment]
It is PVS Studio.
Ok. I will make commit for each warning/error.

**Pull request closed without merging**
