### PR TITLE
Support Postgres arrays in sql replication

### PR DESCRIPTION
**Pull request by brunomlopes**
This is a first attempt at getting arrays to work with the latest npgsql version (3.0, tested with 3.1.4).

### CODE REVIEW

**Comment by ayende** [comment]
@fitzchak Please review this.

**Comment by brunomlopes** [comment]
Any news?
I'll need to plan next steps on our end if something like this ends on 3.5 (which would include planning and testing our upgrade from 3.0 to 3.5)

**Comment by fitzchak** [comment]
@brunomlopes I'm looking into this

**Comment by brunomlopes** [comment]
Thanks.

**Comment by fitzchak** [comment]
@brunomlopes Looking good.

Do you have a CLA with us? 
http://ravendb.net/contributing

**Comment by brunomlopes** [comment]
Yeah, from "Wed, Oct 13, 2010 at 3:18 PM."

I'll try to improve the tests to check the arrays themselves

**Comment by fitzchak** [comment]
OK

**Comment by brunomlopes** [comment]
@fitzchak there you go, now the test checks the array, in case there was some other issue.

**Comment by fitzchak** [comment]
@brunomlopes Please send this PR to ayende/ravnedb v3.5, we'll merge it there.

**Pull request closed without merging**
