### PR TITLE
RavenDB-12280 [WIP][MERGABLE] Client side support for graph query

### PR DESCRIPTION
**Pull request by talweiss1982**
@ppekrol @ayende @maximburyak @myarichuk 
Please review this PR, it is still incomplete, I need to add assertions and properly deal with aggregating parameters and even then we need to expend the functionality but first, we need a baseline to start with.

### CODE REVIEW

**Comment by talweiss1982** [comment]
I have a problem with adding IRavenQueryable in the "With" method, I can't access the DocumentQuery instance, therefore, I can't enforce rules on it nor can I aggregate the parameters into the parent DocumentQuery.
Thoughts?

**Comment by ppekrol** [comment]
```
IGraphQuery<T> With<TOther>(string alias, IRavenQueryable<TOther> query);
```


You are reffering to this?
I think it should be `IDocumentQuery` instead of `IRavenQueryable`. We do not want to mix both of our query types (LINQ and IDocumentQuery).

**Comment by talweiss1982** [comment]
@ppekrol yes this seems to be the viable solution but it is not as nice of an interface

**Comment by ppekrol** [comment]
You should look into builders e.g.
https://github.com/ravendb/ravendb/blob/v4.1/src/Raven.Client/Documents/Queries/MoreLikeThis/MoreLikeThisFactory.cs
or
https://github.com/ravendb/ravendb/blob/v4.1/src/Raven.Client/Documents/Queries/Facets/FacetFactory.cs

**Comment by ayende** [comment]
I think that users will want to mostly pass Linq expression into this.
We will need another overload for `IDocumetnQuery`, and there is `aysnc` version to consider :-(

**Comment by ppekrol** [comment]
We should not mix both of them. LINQ expression can be added at later stage to session.Query, not session.Advanced.DocumentQuery

**Comment by maximburyak** [comment]
more relevant pr exists: https://github.com/ravendb/ravendb/pull/8543

**Pull request closed without merging**
