### PR TITLE
RavenDB-17373 Optimize range queries

### PR DESCRIPTION
**Pull request by ayende**
### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-17373 

### Additional description

Interduce a cache per Lucene segment that will allow us to optimize range queries.
This is done under the `Experimental` flag, the cache is done only for repeated queries and can significantly reduce the cost of common range queries (usually involving dates).

### Type of change

- Optimization

### How risky is the change?

- High

This change a pretty fundamental piece inside RavenDB. We need to carefully review this.
 
### Backward compatibility

- Non breaking change
This should be optimization only step

### Is it platform specific issue?

- No

### Documentation update

Might want to mention the new configuration options, but not beyond this

### Testing 

- Tests have been added that prove the fix is effective or that the feature works

### CODE REVIEW

**Review by arekpalinski — APPROVED** [review]

**Comment by ayende** [comment]
Without optimization:
image


With optimization:

image

For this query:

```
from index 'Users/Search'
where search(DisplayName, "Oren") and CreationDate between "2008-10-13T07:18:01.623" and "2018-10-13T07:18:01.623"
include timings()
```

Over 70 million docs.

**Comment by ppekrol** [comment]
@ayende we have rebased your PR + also we took latest sources of MemoryCache from .NET 7 branch

**Comment by ppekrol** [comment]
There is one more option available there 'TrackLinkedCacheEntries' according to the comment it was set to true prior to .NET 7, now default value is 'false'

**Review by ppekrol — APPROVED** [review]

**Comment by ayende** [comment]
`TrackLinkedCacheEntries` is meaningless for us and _should_ be false.
Went over the code again, looks good to me

**Pull request merged**
