### PR TITLE
RavenDB-5278: Enable Ignored Test.

### PR DESCRIPTION
**Pull request by redknightlois**

### CODE REVIEW

**Comment by ayende** [comment]
The test still fails, what is the point of enabling it without fixing it?

**Comment by redknightlois** [comment]
Knowing that it exists :) ... that issue was buried under 300 issues, also found a few more in the same condition.

**Comment by ayende** [comment]
We have a few failing tests that fail _right_ now, this will add to the noise.
At any rate, we aren't going to allow skipped tests as part of the ramp up to rTM

**Comment by redknightlois** [comment]
Good enough for me 👍

**Pull request closed without merging**
