### PR TITLE
RavenDB-8682 fixing query on id() with aliases on dynamic query

### PR DESCRIPTION
**Pull request by talweiss1982**
* contains fix for broken collection queries on id()

### CODE REVIEW

**Comment by ayende** [comment]
what about when user does `where ID() == 'users/1'` ?

**Comment by talweiss1982** [comment]
I don't think it was ever supported, i can modify it to OrdinalIgnoreCase

**Comment by talweiss1982** [comment]
this doesn't even parsed as a MethodExpression

**Comment by ayende** [comment]
It most certainly should be parsed as a method, in RQL method names are not case sensitive.

**Comment by talweiss1982** [comment]
I was doing this query on the wrong database... it is parsed as binary expression not as a method expression which is right.

**Pull request merged**
