### PR TITLE
RavenDB-15667 Hub Replication Access Info is Not exported/imported wh…

### PR DESCRIPTION
**Pull request by efratshenhar**
…en exporting/importing a database

### CODE REVIEW

**Comment by ml054** [comment]
do we want to have toggle for that on UI? Right now we export / import that everytime.

**Comment by karmeli87** [comment]
This was only a studio issue? do we a have server-side test for this?

**Comment by efratshenhar** [comment]
yes

**Comment by ppekrol** [comment]
> do we want to have toggle for that on UI? Right now we export / import that everytime.

We should expose this in the UI

**Comment by Danielle9897** [comment]
Opened https://issues.hibernatingrhinos.com/issue/RavenDB-15680

**Pull request merged**
