### PR TITLE
RavenDB-5384 Compression

### PR DESCRIPTION
**Pull request by arekpalinski**

### CODE REVIEW

**Comment by ayende** [comment]
This is for review only, so I assume that you know about the failing tests?

**Comment by arekpalinski** [comment]
Yes. I'm aware of that. Failing tests are related to updates / deletes and index debug extensions for map reduce visualizer - they cannot deal with compressed pages yet.

**Comment by ayende** [comment]
Okay, that is fine, just wanted to verify.

**Comment by arekpalinski** [comment]
FYI: Caching mechanism is faulty. In particular there is no need to have two separate caches for read / write usages (that's actually very wrong approach). It's going to be changed.

**Comment by ayende** [comment]
I had a hard time reviewing each commit, so I squashed them all and did a one pass review.
Please take a look here for my comments:
https://github.com/ayende/ravendb/commit/2bb59602fd1a2a2b2e85463a38d46928c5318565

**Pull request closed without merging**
