### PR TITLE
Make SmugglerRemoteDatabaseOperations.ShowProgress virtual

### PR DESCRIPTION
**Pull request by tehkyle**
… ravendb 2.5. We used this to monitor the progress in our application's Import feature which wrapped up the smuggler. This was changed in the SmugglerRemoteDatabaseOperations refactor and as such, we currently have no way to hook into the smuggler progress in 3.0+

### CODE REVIEW

**Comment by ayende** [comment]
Hi,
Do you have a CLA with us?

**Comment by ayende** [comment]
http://ravendb.net/contributing

**Comment by tehkyle** [comment]
Ah, not yet. My coworker has one from a previous pull request. Sent to support@ravendb.net

**Comment by ayende** [comment]
Thanks, you'll probably need to do the same on 3.5

**Pull request merged**
