### PR TITLE
Removing redundant using statements

### PR DESCRIPTION
**Pull request by ap-samples**
Those "using" statements are in fact redundant.

### CODE REVIEW

**Comment by ayende** [comment]
Hi,
Do you have a CLA with us?

**Comment by ap-samples** [comment]
Hi,
no. 
Am I right, you require CLA for *removing* several "using" statements, right?

**Comment by ayende** [comment]
We require a CLA for any PR to be accepted.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ayende** [comment]
FWIW, _removing_ code can be much better to a codebase than adding it.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ap-samples** [comment]
Where that CLA can be found? You may consider putting info about CLA to readme, if you care about being contributor-friendly.

**Comment by ayende** [comment]
ravendb.net/contributing

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Pull request closed without merging**
