### PR TITLE
 RavenDB-12348 Linux - remove user related properties from ProcessStartInfo

### PR DESCRIPTION
**Pull request by iftahbe**

### CODE REVIEW

**Review by ayende — APPROVED** [review]

**Comment by iftahbe** [comment]
Got some Windows failures now, please don't merge

**Comment by iftahbe** [comment]
@ppekrol when we set bInheritHandles to false we also turned off the inheritance of the standard handles. I think we need to turn it back on and set the flags to include only STARTF_USESTDHANDLES.

See: https://docs.microsoft.com/en-us/windows/desktop/ProcThread/inheritance

**Comment by ppekrol** [comment]
@iftahbe This is exactly that MS is setting when input/output/error is redirected: https://github.com/dotnet/corefx/blob/53d1d60e3dca6c9cc61cfac628b393de27fff649/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Windows.cs#L501

But in order for it to work, we need to set 'inheritHandles' to 'true' which we don't want to do (we need to avoid socket inheritance).

@iftahbe @ayende Can we assume that we have two opposite requirements and we cannot do much here, except reverting to built-in Process and waiting for MS to fix the handle issue?

**Comment by ayende** [comment]
Yes, I don't think that we have any way to handle this that would actually work for us, in this case.
Let's mark this as waiting for MS and close this.

**Comment by ayende** [comment]
Is there any code that was already merged that we need to revert?

**Comment by ppekrol** [comment]
Yes, I will do the reverts.

**Pull request closed without merging**
