### PR TITLE
RavenDB-18899: Allocation optimization at IndexWriter

### PR DESCRIPTION
**Pull request by redknightlois**

### CODE REVIEW

**Comment by redknightlois** [comment]
Optimization of the EnumerableWriterScope to use less managed memory and avoid some memory copies. 
image

**Review by maciejaszyk — APPROVED** [review]

**Comment by arekpalinski** [comment]
Is is still DO-NOT-MERGE ?

**Comment by redknightlois** [comment]
Yes. I will let @ayende to try this one out on the Kobo dataset before changing it...

**Comment by redknightlois** [comment]
Now, it is ready to be merged. @arekpalinski

**Comment by arekpalinski** [comment]
@redknightlois can you please check the conflicts?

**Comment by redknightlois** [comment]
Done.

**Comment by arekpalinski** [comment]
test this please

**Pull request merged**
