### PR TITLE
RavenDB-13029 GetCollections throws NRE

### PR DESCRIPTION
**Pull request by talweiss1982**
* Note while this commit seems to make the problem go away there might be a more complex issue here that is why i added a debug assert to make sure this surface in tests.

### CODE REVIEW

**Comment by talweiss1982** [comment]
i'm seeing debug assertion failing after this change so don't merge this yet

**Comment by talweiss1982** [comment]
debug assert fails

**Comment by ayende** [comment]
You cannot change the order of operations here. It is important for a lot of factors. 

What is the cause of the NRE in the first place?

**Comment by talweiss1982** [comment]
@ayende  note that in the async commit the order is replaced:
https://github.com/ravendb/ravendb/blob/v4.1/src/Voron/Impl/LowLevelTransaction.cs#L944
see my comment on the issue for further details

**Comment by ayende** [comment]
I think that we can get away with it there because we are still holding the tx lock from the _current_ transaction in the `EndAsyncCommit`. 
Can you also try reversing it there and see if that works?

**Pull request closed without merging**
