### PR TITLE
RavenDB-22959 - Add IncludeAllTimeSeries(DateTime? from = null, DateTime? to = null) method

### PR DESCRIPTION
**Pull request by shaharhikri**
### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-22959/Add-support-for-including-all-timeseries-by-from-to-dates

### Additional description

Add Add IncludeAllTimeSeries(DateTime? from = null, DateTime? to = null)
equivalent to IncludeTimeSeries(string name, DateTime? from = null, DateTime? to = null); but for *all* timeseries

### Type of change

- [ ] Bug fix
- [ ] Regression bug fix
- [ ] Optimization
- [x] New feature

### How risky is the change?

- [ ] Low 
- [ ] Moderate 
- [ ] High
- [x] Not relevant

### Backward compatibility

- [ ] Non breaking change
- [ ] Ensured. Please explain how has it been implemented?
- [ ] Breaking change
- [x] Not relevant

### Is it platform specific issue?

- [ ] Yes. Please list the affected platforms.
- [x] No

### Documentation update

- [x] This change requires a documentation update. Please mark the issue on YouTrack using `Documentation Required` tag.
- [ ] No documentation update is needed 

### Testing by Contributor

- [x] Tests have been added that prove the fix is effective or that the feature works
- [ ] Internal classes added to the test class (e.g. entity or index definition classes) have the lowest possible access modifier (preferable `private`) 
- [ ] It has been verified by manual testing

### Testing by RavenDB QA team

- [ ] This change requires a special QA testing due to possible performance or resources usage implications (CPU, memory, IO). Please mark the issue on YouTrack using `QA Required` tag.
- [x] No special testing by RavenDB QA team is needed

### Is there any existing behavior change of other features due to this change?

- [ ] Yes. Please list the affected features/subsystems and provide appropriate explanation
- [x] No

### UI work

- [ ] It requires further work in the Studio. Please mark the issue on YouTrack using `Studio Required` tag.
- [x] No UI work is needed

### CODE REVIEW

**Comment by karmeli87** [comment]
Note that we need to add XML comments for 6.0 version

**Comment by ppekrol** [comment]
By glance LGTM, but tests hanged so please take care of this. It is your responsibility to check if PR is fine, I do not want to act as a notification center.

**Comment by shaharhikri** [comment]
https://github.com/ravendb/ravendb/pull/19688#issuecomment-2519656447
I have already looked at the failing tests here and the problem seems like an internal issue with Jenkins:
https://jenkins.hibernatingrhinos.com/job/PR_Tests/13019/testReport/
Also, if any PR has hanging tests, know that I'll get to it and fix it, so there is no need for a comment or reminder.

**Comment by shaharhikri** [comment]
test this please

**Review by karmeli87 — APPROVED** [review]

**Pull request merged**
