### PR TITLE
PR; StringSupport for: Contains, Split, Trim, ToUpper, ToLower & Replace

### PR DESCRIPTION
**Pull request by xinix00**
Added:
Contains -> .indexOf("???") !== -1
ToUpper -> .toUpperCase()
ToLower -> .toLowerCase()
Trim -> .trim()
Replace -> .replace(/regex/g, target) to mimic replace all
Split -> .split(/regex/g) to mimic splitAll + multi string split: /regex|regex/g)

Moved .join around, to better fit with multiple functions, tried to keep "for loops" for looping, where possible used context.Visitor.

Used if(mce.Method.Name =="Contains") since IndexOf could also be added, which will duplicate the newName (both indexOf in that case). Also added the apropriate tests to FastTests.

One remark on SplitEscape and ReplaceEscape, they both escape the regex fine, though your parser isn't happy about some characters (server side), if I try the regex on regex101.com, it's valid and escaped correctly.

Since used Regex.Escape().Replace() 3 times, maybe add it as a function in StringUtils (or something) couldn't find a class to add this function to. Purpose, to escape regex AND escape /, used to translate both split and replace.

### CODE REVIEW

**Comment by ayende** [comment]
@aviv86 Please review this

**Comment by aviv86** [comment]
very nice work,

just one small problem, in split and replace, the casting of the arguments to ConstantExpression  will throw an InvalidCastExecption on things like:

 - var chars = new char[2] {'e', 'r'};
    u.Name.Split(chars);

 - u.Name.Replace(u.Name, u.LastName)
etc..

maybe we should check the type of the argument , if it's not a ConstantExpression then call context.Visitor.Visit(arg)

**Comment by xinix00** [comment]
Great thinking,

Making a small consession you can translate this:
.Split(new [] { "a", "b", u.Username }, ...) to .split(new RegExp("a" + "|" + "b" + "|" + u.Username, "g"))

Then all will be done by the visitor pattern. The downside is, you cannot escape the RegExp anymore. Upside, all can work the visitor. (I used the ConstantExpression cast because your visitor will add quotes, which I don't need in a // regex statement. Converting it to the Regex object would work nicely with quotes and thus with the visitor pattern)

Or add the function: 
function escapeRegExp(str) {
  return str.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");
}
to create:

.Split(new [] { "a", "b", u.Username }, ...) to .split(new RegExp(escapeRegExp("a" + "|" + "b" + "|" + u.Username), "g"))
This one will mimic the same behavior as c#.

Any thoughts?

Code would then change to:
```
                        if (newName == "split")
                        {
                            writer.Write("new RegExp(");
                            if (mce.Arguments[0] is NewArrayExpression arrayExpression)
                            {
                                for (var i = 0; i < arrayExpression.Expressions.Count; i++)
                                {
                                    if (i != 0)
                                    {
                                        writer.Write("+\"|\"+");
                                    }

                                    context.Visitor.Visit(arrayExpression.Expressions[i]);
```

OR

Don't use ReplaceAll, so .Replace() will be translated to .replace("test", "test") without using RegExp. Downside: it won't replace ALL (like C# does), upside, it's much easier to translate to JS.

**Comment by xinix00** [comment]
In addition, this is what it looks like now:

Input:
Split = u.Name.Split('r', StringSplitOptions.None),
SplitArray = u.Name.Split(new char[] { 'r', 'e' }),
SplitArgument =  u.Name.Split(u.Roles, StringSplitOptions.None),
SplitStringArray = u.Name.Split(new string[] { "er", "rr" }, StringSplitOptions.None),

Replace = u.Name.Replace('r', 'd'),
ReplaceString = u.Name.Replace("Jerry", "Charly"),
ReplaceArguments = u.Name.Replace(u.Name, u.LastName),
ReplaceArgumentsComplex = u.Name.Replace(u.Name + "a", u.LastName + "a")

Outputs:

Split : u.Name.split(new RegExp("r", "g")),
SplitArray : u.Name.split(new RegExp("r"+"|"+"e", "g")), 
SplitArgument : u.Name.split(new RegExp(u.Roles, "g")), 
SplitStringArray : u.Name.split(new RegExp("er"+"|"+"rr", "g")), 
Replace : u.Name.replace(new RegExp("r", "g"), "d"), 
ReplaceString : u.Name.replace(new RegExp("Jerry", "g"), "Charly"), 
ReplaceArguments : u.Name.replace(new RegExp(u.Name, "g"), u.LastName), 
ReplaceArgumentsComplex : u.Name.replace(new RegExp((u.Name+"a"), "g"), (u.LastName+"a"))

**Comment by aviv86** [comment]
Yes i like the idea of translating .Split(new [] { "a", "b", u.Username }, ...) to .split(new RegExp("a" + "|" + "b" + "|" + u.Username, "g"))
can you please commit the changes?

**Comment by xinix00** [comment]
Much cleaner, though with a downside included (doesn't escape regex).

**Pull request merged**
