### PR TITLE
RavenDB-7070 prevent test hanging upon PinOnGoingTaskToMentorNode failure

### PR DESCRIPTION
**Pull request by karmeli87**
### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-7070

### CODE REVIEW

**Comment by ppekrol** [comment]
@karmeli87 please check failing test

**Comment by karmeli87** [comment]
Was unable to repro the failure locally (added debug info), but it is a success that it has failed and not hanged :-) (which is what this PR was intended to handle)

**Comment by ppekrol** [comment]
We need to proceed digging then, because I do not think 5.2 builds are hanging, so it means that higher timeout resolves the issue, why is this the case?

**Comment by karmeli87** [comment]
fixed here https://github.com/ravendb/ravendb/pull/16481

**Pull request closed without merging**
