### PR TITLE
Adds support for linq queries using a dictionary entity type.

### LINKED ISSUE #14489: RavenDb Linq query using a dictionary or a dictionary inherited model.
We have faced a problem working with linq using a model that inherits from a dictionary, so that when we do a certain where condition  where one of the operands is an element with a specific key it results in an exception.

image

### PR DESCRIPTION
**Pull request by a-haddaji-neoventive**
### Issue link

https://github.com/ravendb/ravendb/issues/14489

### Additional description

RavenDb Linq query using a dictionary or a dictionary inherited model

### Type of change

- Bug fix

### How risky is the change?

- Low 

### Backward compatibility

- Non breaking change

### Is it platform specific issue?

- No

### Documentation update

- No documentation update is needed 

### Testing 

- It has been verified by manual testing

### Is there any existing behavior change of other features due to this change?

- No

### UI work

- No UI work is needed

### CODE REVIEW

**Comment by ppekrol** [comment]
test this please

**Comment by ppekrol** [comment]
@a-haddaji-neoventive could you add a test? We do not know what case it exactly covers.

**Comment by a-haddaji-neoventive** [comment]
> Hi!
> 
> Thank you for contributing into RavenDB project. Unfortunetely we detected that not all committers signed our CLA.
> 
> Following contributors are not in our database:
> 
> * DESKTOP-SQ34IUF\achre ([a.haddaji.neoventive@gmail.com](mailto:a.haddaji.neoventive@gmail.com))
> 
> Please visit http://ravendb.net/contributors/cla/sign to sign CLA.

I have tried to make a submission on the website, but unfortunately the website is rejecting my request, see the picture below:

image

**Comment by ppekrol** [comment]
This is new to us. Give us few moments to check what is going on.

**Comment by ppekrol** [comment]
@a-haddaji-neoventive It looks like we were doing a quick update of our APIs during that time. Can you check again? The form works fine now.

**Comment by a-haddaji-neoventive** [comment]
> @a-haddaji-neoventive It looks like we were doing a quick update of our APIs during that time. Can you check again? The form works fine now.

@ppekrol I am afraid that the issue is still there and it seems to be something wrong with the recpatcha, it can't be validated on my side.
image

this pull request covers what is mentioned on the issue ticket, using a dictionary as a queryable model then do some filtering with it, i will try to add some unit testes later if you want.

**Comment by ppekrol** [comment]
Test(s) would be great. We will check what is going on with the recaptcha. Really surprising. 

Thank you for the contribution.

**Review by ppekrol — APPROVED** [review]

**Comment by maciejaszyk** [comment]
Hey @a-haddaji-neoventive,
I reviewed your PR and it seems that your test is not executing the code you wrote. Query from the ticket seems much more complex and doing something with the changes. Can you review your test and added code, and make the necessary changes?

**Comment by a-haddaji-neoventive** [comment]
> Hey @a-haddaji-neoventive, I reviewed your PR and it seems that your test is not executing the code you wrote. Query from the ticket seems much more complex and doing something with the changes. Can you review your test and added code, and make the necessary changes?

The second Unit test that i wrote does cover the changes, the query from the ticket is just a simple equality expression but there are so many other ways to query with a dictionary of course, the fix allows to recognize element indexes as member operand, the rest of the expression is treated just like any other query, i can do more unit test with more variety of queries if you want.

```
        [Fact]
        public void Query_Dictionary_With_Where_Clause()
        {
            using (var store = GetDocumentStore())
            {
                using (var newSession = store.OpenSession())
                {
                    newSession.Store(new Dictionary<string, object?> { { "Name", "John" } }, "users/1");
                    newSession.Store(new Dictionary<string, object?> { { "Name", "Jane" } }, "users/2");
                    newSession.Store(new Dictionary<string, object?> { { "Name", "Tarzan" } }, "users/3");
                    newSession.SaveChanges();

                    var query = newSession.Query<Dictionary<string, object?>>()
                        .Where(x => ((string)x["Name"]).StartsWith("J")).ToString();

                    var queryResult = newSession.Query<Dictionary<string, object?>>()
                        .Where(x => ((string)x["Name"]).StartsWith("J"))
                        .ToList();

                    var queryResult2 = newSession.Query<Dictionary<string, object?>>()
                        .Where(x => ((string)x["Name"]).Equals("Tarzan"))
                        .ToList();

                    var queryResult3 = newSession.Query<Dictionary<string, object?>>()
                        .Where(x => ((string)x["Name"]).EndsWith("n"))
                        .ToList();

                    Assert.Equal(queryResult.Count, 2);
                    Assert.Equal(queryResult2.Count, 1);
                    Assert.Equal(queryResult3.Count, 2);
                }
            }
        }
```

**Comment by maciejaszyk** [comment]
Moved into https://github.com/ravendb/ravendb/pull/14546 :)

**Pull request closed without merging**
