### PR TITLE
RavenDB-15951 added GC.GetGCMemoryInfo endpoint

### PR DESCRIPTION
**Pull request by ppekrol**

### CODE REVIEW

**Comment by ppekrol** [comment]
Is there anything here we would want to expose via SNMP? cc @gregolsky @karmeli87 @ayende

**Comment by karmeli87** [comment]
If I understand the format correctly maybe the (`Index` ,`PauseDurations`) of the `FullBlocking` will be the most useful?

**Comment by gregolsky** [comment]
I presume we would not monitor all these by default, but turn them on if needed. Preferably put into an additional monitoring template.
With that said, would it hurt to expose all of it? We can then pick interesting ones without any additional code changes.

**Comment by ayende** [comment]
Is there significant difference in the mode between each of those? Is this expensive to query?

**Comment by ppekrol** [comment]
I would have to profile it and check. Will do that a bit later.

When it comes to the difference between modes (kinds). It shows last of the requested kind. This is why I thought it would be better to expose all of them at once, including 'any'.

**Comment by ppekrol** [comment]
This is interesting: https://devblogs.microsoft.com/dotnet/the-updated-getgcmemoryinfo-api-in-net-5-0-and-how-it-can-help-you/

**Comment by ppekrol** [comment]
I do not think this is that expensive:
image

**Pull request merged**
