### PR TITLE
RavenDB-12068 ensure null coalescing is surrounded with parenthesis

### PR DESCRIPTION
**Pull request by lahma**
http://issues.hibernatingrhinos.com/issue/RavenDB-12068

/cc @aviv86

### CODE REVIEW

**Review by ppekrol — APPROVED** [review]

**Comment by ppekrol** [comment]
Following two tests are failing:
```
SlowTests.Client.QueriesWithCustomFunctions.Custom_Functions_Null_Coalescing_Support
SlowTests.Issues.RavenDB_10625.CanTranslateGroupsCorrectly
```

**Comment by lahma** [comment]
I will look into them...

**Comment by lahma** [comment]
Sheesh, you had a pre-commit hook that always changed the contents of QueriesWithCustomFunctions.cs, took some time to realize that. Maybe the latest force push will now comply with build server. Others running/queued should be ignored.

**Comment by ppekrol** [comment]
We removed that in favor of .editorconfig but old clones still contain it. You are correct, the pre-commit hook can be a pain when you are not aware that it exists.

**Comment by lahma** [comment]
@ppekrol this is a chicken and egg kind of situation. I cannot pass whitespace test if I keep the file intact and if I modify it then the tests won't pass.

**Comment by ppekrol** [comment]
Yes, I suggest removing the hook.

**Comment by lahma** [comment]
So you will remove it from your build server?  "commit/whitespace — Commit whitespace conventions were not fulfilled" from unsuccessful build checks.

**Comment by ppekrol** [comment]
No, please ignore this. I'm aware that this `QueriesWithCustomFunctions.cs` contains tabs becase it has too.

**Pull request merged**
