### PR TITLE
RavenDB-11970 Lets Encrypt client : retry sending request once

### PR DESCRIPTION
**Pull request by iftahbe**
Not relevant for 4.0.x, the LE client was replaced

### CODE REVIEW

**Review by ayende — COMMENTED** [review]
What is the error that we are trying to recover from here?

**Comment by iftahbe** [comment]
http://issues.hibernatingrhinos.com/issue/RavenDB-11970#focus=streamItem-67-32117-0-0

**Comment by ayende** [comment]
That is a network error when the remote server refuses us.
Any idea what can be causing this?

**Comment by iftahbe** [comment]
It might be because we test against the staging servers but I have no idea. That's why I was thinking to retry once when it happens.

**Comment by iftahbe** [comment]
I reproduced it again with the fix, and the retry worked well.

**Pull request merged**
