### PR TITLE
Changed all "whatever" to "whether" where it makes sense

### PR DESCRIPTION
**Pull request by DovydasNavickas**
Grammar mistake. Every place where "whether" had to be used, there was word "whatever"

### CODE REVIEW

**Comment by DovydasNavickas** [comment]
Ehm... I see that someone was using the word "whatever" instead of "whether" all over the code. I might go though all 90 files to change that, but not today.

**Comment by ayende** [comment]
Do you have a CLA with us?

**Comment by DovydasNavickas** [comment]
Yes

**Comment by ayende** [comment]
Thanks

**Pull request merged**
