### PR TITLE
RavenDB-12074 WIP

### PR DESCRIPTION
**Pull request by myarichuk**

### CODE REVIEW

**Comment by myarichuk** [comment]
This commit is the most important here -> https://github.com/ravendb/ravendb/pull/7843/commits/3c78f1f1430710278944caec8c68152636008a48

The rest are artifacts (unless I am mistaken) from pull/rebase

**Comment by ppekrol** [comment]
@myarichuk the issue here is that your commits are based on a PR https://github.com/ravendb/ravendb/pull/7835 which is not yet merged

**Comment by ayende** [comment]
Closing this, since I'll merging to #7835 directly and sending PR for the whole thing

**Comment by myarichuk** [comment]
Hm, ok, I guess then this PR can wait. I will add some more tests

**Comment by ayende** [comment]
This PR was already merged here: https://github.com/ravendb/ravendb/pull/7835
You need to work on top of v4.2 now.

**Pull request closed without merging**
