### PR TITLE
RavenDB-12568 using BlittableMetadataModifier when putting document d…

### PR DESCRIPTION
**Pull request by talweiss1982**
…irectly to avoid deviation of behavior between batch insert and manual insert

### CODE REVIEW

**Review by ayende — APPROVED** [review]

**Review by ppekrol — APPROVED** [review]

**Comment by talweiss1982** [comment]
@ppekrol those tests are doing something they shouldn't resolving conflicts by inserting raw blittables with unchecked metadata, i'm trying to see if i can adjust them to work properly but its a catch 22...

**Comment by ppekrol** [comment]
We need to look into those, maybe those tests need to be rewritten now.

**Comment by talweiss1982** [comment]
@ppekrol after looking at it we actually have no other way to resolve conflicts containing attachments manually. We could add a special command for manually choose the change vector that should win but I think this is breaking changes since people may have already relayed on this method of conflict resolving.
I think we should just leave PutDocument as it is document that it should avoid messing with the metadata and should only contain metadata for the purpose of resolving conflicts.
@ayende thoughts?

**Comment by ayende** [comment]
@talweiss1982 At a minimum, we *must* ensure that we can't create attachments that do not exists.

**Comment by ayende** [comment]
Or without references to them

**Pull request closed without merging**
