### PR TITLE
RavenDB-16352 - add id() to the list of index terms

### PR DESCRIPTION
**Pull request by grisha-kotler**

### CODE REVIEW

**Review by ppekrol — COMMENTED** [review]
What about other types of indexes? What about map-reduce?

**Comment by grisha-kotler** [comment]
Map-reduce doesn't have an id field

**Comment by ppekrol** [comment]
But there are additional fields like:
```
                    public const string DocumentIdFieldName = "id()";

                    public const string SourceDocumentIdFieldName = "sourceDocId()";

                    public const string ReduceKeyHashFieldName = "hash(key())";

                    public const string ReduceKeyValueFieldName = "key()";

                    public const string ValueFieldName = "value()";
```

why we want to add only `id()` ? What about other fields?

**Comment by grisha-kotler** [comment]
I'm looking for stored fields I can search on.

**Pull request merged**
