### PR TITLE
RavenDB-11782: Replace old libsodium lib with latest 1.0.16 version

### PR DESCRIPTION
**Pull request by aviviadi**

### CODE REVIEW

**Comment by ppekrol** [comment]
Shouldn't we upgrade all versions to the 1.0.16?

**Comment by ayende** [comment]
Probably a good idea

**Comment by ppekrol** [comment]
@aviviadi current `libsodium.arm.so` is 346 KB. The one that you submitted is 1.04 MB. I wouldn't expect such a huge difference.  Do you know why they differ so much?

**Comment by aviviadi** [comment]
@ppekrol IDK. The new 1MB assembled library was built manually by me on the RPi.  I didn't add switches nor arguments to the build process (can't be sure this is not a debug version..).
I still recommend to get it in, and I will mention in the issue to check this issue

**Comment by ppekrol** [comment]
Can't we install it via apt-get and use the file from there? IIRC this is what we did last time?

**Comment by aviviadi** [comment]
There's no available v1.0.16 in apt repo

**Comment by ppekrol** [comment]
https://packages.ubuntu.com/bionic/libsodium23 ?

**Comment by aviviadi** [comment]
I am talking about raspbian-stretch

**Comment by ppekrol** [comment]
Isn't this the 'armhf' ? What are you getting after doing `apt-get install libsodium23` ?

**Comment by ayende** [comment]
We want to have the `.so` file bundled with us, but yes, we want to use the professionally deployed version.
Need to update 4.0 & 4.1 and all the dll / so

**Comment by ppekrol** [comment]
Yes, me and @aviviadi will be working on this later today or tomorrow morning.

**Pull request closed without merging**
