### PR TITLE
RavenDB-18938 Scan C# source code as string instead Rewriter function for MethodQuery

### PR DESCRIPTION
**Pull request by maciejaszyk**
### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-18938 

### Type of change

- Bug fix

### How risky is the change?

- Low 

### Backward compatibility

- Not relevant

### Is it platform specific issue?

- No

### Documentation update

- No documentation update is needed 

### Testing 

- It has been verified by manual testing

### Is there any existing behavior change of other features due to this change?

- No

### UI work

- No UI work is needed

### CODE REVIEW

**Comment by ppekrol** [comment]
Wrong branch

**Comment by maciejaszyk** [comment]
> Wrong branch

done

**Comment by ppekrol** [comment]
@maciejaszyk Can you check failing tests?

**Comment by maciejaszyk** [comment]
> @maciejaszyk Can you check failing tests?

Fixed.

**Review by arekpalinski — APPROVED** [review]

**Pull request merged**
