### PR TITLE
RavenDB-20730 Fixing confusion when we have a dynamic field with the …

### PR DESCRIPTION
**Pull request by ayende**
…same name of a static field and we are updating the entry

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-20730

### CODE REVIEW

**Comment by ayende** [comment]
I looked at the test failures, doesn't seem to be related to my changes, I run the failures locally, they pass

**Comment by maciejaszyk** [comment]
This fix has a problem with removing dynamic terms. 

The last `Write` clause should remove `Maciej` but it still appears in the query result.

```csharp
    [Fact]
    public void MixingStaticAndDynamicFieldsCorax()
    {
        using IDisposable __ = StorageEnvironment.GetStaticContext(out ByteStringContext ctx);
        Slice.From(ctx, "Id", ByteStringType.Immutable, out Slice aSlice);
        Slice.From(ctx, "Name", ByteStringType.Immutable, out Slice dSlice);

        using var builder = IndexFieldsMappingBuilder.CreateForWriter(false)
            .AddBinding(0, aSlice)
            .AddBinding(1, dSlice);
        var fields = builder.Build();

        using var bsc = new ByteStringContext(SharedMultipleUseFlag.None);
        using (var writer = new IndexWriter(Env, fields))
        {
            var entry = new IndexEntryWriter(bsc, fields);
            entry.Write(0, "users/1"u8);
            entry.Write(1, "Oren"u8);
            entry.WriteDynamic("Rank", "U"u8);
            using var _ = entry.Finish(out var preparedItem);
            writer.Index(preparedItem.ToSpan());
            writer.Commit();
        }
        
        using (var writer = new IndexWriter(Env, fields))
        {
            var entry = new IndexEntryWriter(bsc, fields);
            entry.Write(0, "users/1"u8);
            entry.Write(1, "Oren"u8);
            entry.WriteDynamic("Name", "Maciej"u8);
            using var _ = entry.Finish(out var preparedItem);
            writer.Update("Id", "users/1"u8, preparedItem.ToSpan());
            writer.Commit();
        }

        using (var searcher = new IndexSearcher(Env, fields))
        {
            Span<long> ids = stackalloc long[16];
            var read = searcher.TermQuery("Name", "Maciej").Fill(ids);
            Assert.Equal(1, read);
        }

        using (var writer = new IndexWriter(Env, fields))
        {
            var entry = new IndexEntryWriter(bsc, fields);
            entry.Write(0, "users/1"u8);
            entry.Write(1, "Eini"u8);
            entry.WriteDynamic("Name", "Eini"u8);
            using var _ = entry.Finish(out var preparedItem);
            writer.Update("Id", "users/1"u8, preparedItem.ToSpan());
            writer.Commit();
        }
        
        using (var searcher = new IndexSearcher(Env, fields))
        {
            Span<long> ids = stackalloc long[16];
            var read = searcher.TermQuery("Name", "Maciej").Fill(ids);
            Assert.Equal(0, read);
            read = searcher.TermQuery("Name", "Eini").Fill(ids);
            Assert.Equal(1, read);
        }
    }
```

**Comment by ayende** [comment]
Thanks, looking into this

**Comment by ayende** [comment]
Great catch

There is another problem, however. We aren't handling *deletion* for dynamic field properly either

**Comment by arekpalinski** [comment]
Can you please check failing tests?

**Comment by arekpalinski** [comment]
In particular this failure: https://jenkins.hibernatingrhinos.com/job/PR_Tests/6954/testReport/SlowTests.Tests.Indexes/OldIndexRunWhileNewIndexesAreRunning/ShouldWork_options___DatabaseMode___Single___SearchEngineMode___Corax_/

**Comment by ayende** [comment]
I tried running that, but I couldn't reproduce the error.
Looking into the source, we have:
https://github.com/ravendb/ravendb/blob/087b9b673c792a9c863c9a7888438a504f350635/src/Sparrow.Server/ByteString.cs#L1114

So that is checked, and this is a code path that is *heavily* used.
Can't think of why that would happen.
At any rate, I rebased & pushed, we'll see if this happens again

**Comment by arekpalinski** [comment]
It happened again:
https://jenkins.hibernatingrhinos.com/job/PR_Tests/6970/testReport/junit/SlowTests.Tests.Indexes/OldIndexRunWhileNewIndexesAreRunning/ShouldWork_options___DatabaseMode___Single___SearchEngineMode___Corax_/

**Comment by arekpalinski** [comment]
I'm merging it. Will open a dedicated issue if this test will be still failing.

**Pull request merged**
