### PR TITLE
RavenDB-15554 OnAfterConversionToEntity is missing on the session (on…

### PR DESCRIPTION
**Pull request by ayende**
…ly on document store)

### CODE REVIEW

**Comment by arekpalinski** [comment]
Can we add a test here that the user sent us - https://github.com/ravendb/ravendb/issues/11064 ?

**Comment by arekpalinski** [comment]
I will add it

**Comment by arekpalinski** [comment]
@ayende I've tried to add the test that user has provided but I see his assumption wasn't valid. Not sure what test should be added to validate what you added here.

**Comment by ayende** [comment]
Maybe add separate handling just for that sesion?

**Pull request merged**
