### PR TITLE
RavenDB-19853 - Update Lucene

### PR DESCRIPTION
**Pull request by grisha-kotler**
### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-19853/Unmanaged-memory-is-being-used-by-deleted-document-terms

### Additional description

Update Lucene - reduce unmanged allocations for `order by` queries
https://github.com/ravendb/lucenenet/pull/47

### Type of change

- Bug fix

### How risky is the change?

- Low 

### Testing by Contributor

- It has been verified by manual testing

### CODE REVIEW

**Comment by maciejaszyk** [comment]
What happens when the deleted term is added again? Do we rebuild the cache?

**Comment by grisha-kotler** [comment]
@maciejaszyk, there is a separate cached instance per each segment.
Since segments are read-only, if the deleted term will be added again it will appear in a new segment.
And we'll generate a new cache for that segment only.

**Comment by ayende** [comment]
What will actually happen is that the next query to run with `order by` will force us to re-load all of them from scratch
The benefit is if this is a rare scenario.

**Comment by arekpalinski** [comment]
So we should see the impact in QA querying scenarios with `order by`, right? CC @garayx

**Comment by grisha-kotler** [comment]
The cache is per segment so if we had:
- `order by` query (caching all existing segments)
- a deletion and afterward recreation of the document, we'll have 2 new segments.
- `order by` query. We'll use the cache for the existing segments and generate the cache for the 2 new segments.
(we won't be rebuilding the cache for all the segments)

@garayx 
The scenario is:
- Create `1M` documents with a string field
- Create an index on the string field and wait for it to become non-stale
- Delete all documents
- Wait for the index to become non-stale
- Generate an `order by` query
The Lucene unmanaged memory won't be 0 and it will take more time to return a result.

**Pull request merged**
