### PR TITLE
RavenDB-21528 added support for brotli and zstd compression

### PR DESCRIPTION
**Pull request by ppekrol**
### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-21528 

### Type of change

- New feature

### How risky is the change?

- Moderate 

### Backward compatibility

- Non breaking change

### Is it platform specific issue?

- No

### Documentation update

- This change requires a documentation update. Please mark the issue on YouTrack using `Documentation Required` tag.

### Testing by Contributor

- It has been verified by manual testing

### Testing by RavenDB QA team

- This change requires a special QA testing due to possible performance or resources usage implications (CPU, memory, IO). Please mark the issue on YouTrack using `QA Required` tag.

### Is there any existing behavior change of other features due to this change?

- No

### UI work

- No UI work is needed

### CODE REVIEW

**Comment by ppekrol** [comment]
BulkInsert `(new Company { Name = $"HR_{i}" })`

Zstd with Level 3 (default):
Items: 10000000. Took: 00:02:05.6711780
Items: 10000000. Took: 00:02:03.5200923
Items: 10000000. Took: 00:02:04.9505252. Items/s: 80031.67640947219

Zstd with Level 1:
Items: 10000000. Took: 00:02:04.6933777. Items/s: 80196.72082393193

Zstd (ZstdSharp) with Level 1:
Items: 10000000. Took: 00:01:57.6998414. Items/s: 84961.88169035205 but got exception at the end:
`Inserted 9,994,591 items in 1,329 batches. Last document ID: 'companies/9994591-A'`

Brotli (Fastest):
Items: 10000000. Took: 00:04:01.2156792. Items/s: 41456.67492745637
Items: 10000000. Took: 00:03:59.5240300. Items/s: 41749.46455267975

Brotli (Optimal):
Items: 10000000. Took: 00:02:32.9597654. Items/s: 65376.66930809767
Items: 10000000. Took: 00:02:33.7498432. Items/s: 65040.716737459414

Gzip (Fastest):
Items: 10000000. Took: 00:02:22.5375631. Items/s: 70156.94517650976
Items: 10000000. Took: 00:02:23.2588735. Items/s: 69803.70399185081

Gzip (Optimal):
Items: 10000000. Took: 00:02:36.2304974. Items/s: 64007.98926215286
Items: 10000000. Took: 00:02:38.1159649. Items/s: 63244.72045769997

NoCompression:
Items: 10000000. Took: 00:03:11.7210908. Items/s: 52159.10236204435
Items: 10000000. Took: 00:03:05.3160469. Items/s: 53961.8676702951

**Comment by ppekrol** [comment]
Session (SaveChanges) `new Company { Name = $"HR_{i}_{j}" }`

Zstd with Level 3 (default):
Batches: 100000. Batch Size: 10 Took: 00:02:51.8919229. Items/s: 5817.609013436663
Batches: 100000. Batch Size: 10 Took: 00:02:46.8395006. Items/s: 5993.784423974714

Zstd with Level 1:
Batches: 100000. Batch Size: 10 Took: 00:02:03.2872534. Items/s: 8111.138600480818
Batches: 100000. Batch Size: 10 Took: 00:02:02.4757539. Items/s: 8164.88135942799

Zstd (ZstdSharp) with Level 1:
Batches: 100000. Batch Size: 10 Took: 00:01:53.6720916. Items/s: 8797.234096113
Batches: 100000. Batch Size: 10 Took: 00:01:56.9092896. Items/s: 8553.64020619282

Brotli (Fastest):
Batches: 100000. Batch Size: 10 Took: 00:01:53.7218365. Items/s: 8793.385956267071
Batches: 100000. Batch Size: 10 Took: 00:01:56.4473352. Items/s: 8587.573071401637

Brotli (Optimal):
Batches: 100000. Batch Size: 10 Took: 00:02:00.0961142. Items/s: 8326.664077862395
Batches: 100000. Batch Size: 10 Took: 00:02:03.2723131. Items/s: 8112.12165045356

Gzip (Fastest):
Batches: 100000. Batch Size: 10 Took: 00:01:57.1522041. Items/s: 8535.904276682746
Batches: 100000. Batch Size: 10 Took: 00:01:57.0371168. Items/s: 8544.297974367051

Gzip (Optimal):
Batches: 100000. Batch Size: 10 Took: 00:01:58.6356581. Items/s: 8429.168902633668
Batches: 100000. Batch Size: 10 Took: 00:02:02.2131723. Items/s: 8182.424047919097

NoCompression:
Batches: 100000. Batch Size: 10 Took: 00:01:47.7787300. Items/s: 9278.268541483092
Batches: 100000. Batch Size: 10 Took: 00:01:51.7435739. Items/s: 8949.060470313094

**Comment by ppekrol** [comment]
Bulk Insert (data written to request)

```
10_000_000 item(s):
Zstd : 			21.64 MBytes

Gzip (Fastest): 	56.13 MBytes
Gzip (Optimal): 	54.23 MBytes

Brotli (Fastest): 	2.371 GBytes (!)
Brotli (Optimal): 	22.16 MBytes

===

1_000_000 item(s):
Zstd : 			2.18 MBytes

Gzip (Fastest): 	5.61 MBytes
Gzip (Optimal): 	5.42 MBytes

Brotli (Fastest): 	242.76 MBytes (!)
Brotli (Optimal): 	2.22 MBytes

===

100_000 item(s):
Zstd: 			253.48 KBytes

Gzip (Fastest): 	574.84 KBytes
Gzip (Optimal): 	555.42 KBytes

Brotli (Fastest): 	24.13 MBytes (!)
Brotli (Optimal): 	224.48 KBytes

===

1 item(s):
Zstd: 			245 Bytes

Gzip (Fastest): 	239 Bytes
Gzip (Optimal): 	240 Bytes

Brotli (Fastest): 	254 Bytes
Brotli (Optimal): 	222 Bytes
```

**Comment by ayende** [comment]
What is missing from this analysis is also the cost in time, no?

**Comment by ppekrol** [comment]
Bulk Insert

image

**Comment by lahma** [comment]
Just a thought and I might not have any idea what I'm talking about, but could dictionary-based compression reuse compressed database's trained dictionary?

**Comment by ppekrol** [comment]
@lahma I do not think it would be possible, because we would have to transfer as well the dictionary for decompression purposes.  Also pretty sure that Brotli does not allow that, and almost certain zstd as well.

**Comment by ppekrol** [comment]
Session

image

**Comment by ppekrol** [comment]
Session (medium size entities)

image

**Pull request merged**
