### PR TITLE
RavenDB-9855 fix data dir volume in docker ubuntu

### PR DESCRIPTION
**Pull request by gregolsky**

### CODE REVIEW

**Comment by ayende** [comment]
what about the tcp port?

**Comment by gregolsky** [comment]
I'll send another PR with more fixes, but without the TCP port. Not sure how to tackle this one. It's problematic since settings.json is overriden after setup so we can set it up there. Also setup doesn't need tcp. 

We can just let the user set it up within his settings.json, yet it would still need to be aligned with port we have exposed - 38888.. Another way would be to always pass it as cli arg like `--ServerUrl.Tcp=tcp://0.0.0.0:38888` or  `--ServerUrl.Tcp=tcp://$hostname:38888`?

**Comment by ayende** [comment]
Why not do that in the same way we do it for the `ServerUrl` ? Just pass it from the script as env variable, then the user can override it, no?

**Comment by ayende** [comment]
`export RAVEN_ServerUrl_Tcp 38888`

**Comment by gregolsky** [comment]
checking

**Comment by gregolsky** [comment]
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Raven.Server.RavenServer.StartTcpListener() in C:\work\ravendb4\src\Raven.Server\RavenServer.cs:line 666
   at Raven.Server.RavenServer.Initialize() in C:\work\ravendb4\src\Raven.Server\RavenServer.cs:line 234
   at Raven.Server.Program.Main(String[] args) in C:\work\ravendb4\src\Raven.Server\Program.cs:line 124

**Pull request merged**
