### PR TITLE
RavenDB-19595 Remove TemporaryPage

### PR DESCRIPTION
**Pull request by ayende**
### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-19595 

### Additional description

Avoid having a pinned buffer in managed memory and using unmanaged memory for temporary memory

### Type of change

- Optimization

### How risky is the change?

- High

Pretty big change in very low level area

### Backward compatibility

- Non breaking change

### Is it platform specific issue?

- No

### Documentation update

- No documentation update is needed 

### Testing 

- All tests should pass

### Is there any existing behavior change of other features due to this change?

- No

### UI work

- No UI work is needed

### CODE REVIEW

**Comment by arekpalinski** [comment]
Please check failing tests and conflicts

**Comment by ayende** [comment]
Should be fine now

**Comment by arekpalinski** [comment]
We're getting now: `The active test run was aborted. Reason: Test host process crashed : Fatal error. Internal CLR error. (0x80131506)`

**Comment by ayende** [comment]
How are you getting this error? All the tests runs that I'm trying locally are passing.

**Comment by arekpalinski** [comment]
It happened when tests were running by Jenkins:

https://jenkins.hibernatingrhinos.com/job/PR_Tests/4847/consoleFull

**Comment by arekpalinski** [comment]
I've run two more builds and both crashed:

https://jenkins.hibernatingrhinos.com/job/PR_Tests/4858
https://jenkins.hibernatingrhinos.com/job/PR_Tests/4859

On the output we have:

```
16:03:33  The active test run was aborted. Reason: Test host process crashed
16:03:33  Results File: c:\Jenkins\workspace\PR_Tests\s\test\SlowTests\service-account_EAGLE-5_2023-01-27_17_03_32.trx
16:03:33  
16:03:33  Test Run Aborted with error System.Exception: One or more errors occurred.
16:03:33   ---> System.Exception: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
16:03:33   ---> System.Exception: An existing connection was forcibly closed by the remote host.
16:03:33     at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
16:03:33     --- End of inner exception stack trace ---
16:03:33     at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
16:03:33     at System.Net.Sockets.NetworkStream.ReadByte()
16:03:33     at System.IO.BinaryReader.Read7BitEncodedInt()
16:03:33     at System.IO.BinaryReader.ReadString()
16:03:33     at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
16:03:33     at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
16:03:33     --- End of inner exception stack trace ---.

```

I checked Event Viewer logs on both eagle machines where tests were running and on that time we have on both:

```
Faulting application name: testhost.exe, version: 15.0.0.0, time stamp: 0x62aa687e
Faulting module name: ntdll.dll, version: 10.0.17763.3887, time stamp: 0x494079d6
Exception code: 0xc0000374
Fault offset: 0x00000000000fc1b9
Faulting process id: 0x1560
Faulting application start time: 0x01d932607f6fbd5d
Faulting application path: c:\Jenkins\workspace\PR_Tests\s\test\SlowTests\bin\Release\net7.0\testhost.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: e30c1fc1-1d69-43aa-aebe-9929acebf5e0
Faulting package full name: 
Faulting package-relative application ID: 
```

I looks the problem is with the heap.

**Comment by ayende** [comment]
Confirmed, that crashes in a few minutes on my machine as well.
Going to hopefully make it much easier to fix

**Comment by ayende** [comment]
Can reproduce with `SlowTests.Voron.Storage.Snapshots.SingleItemBatchTestLowLevel` running in a loop :-)

**Comment by ayende** [comment]
Fixing coming up shortly

**Comment by ayende** [comment]
Hopefully, that would all work now

**Review by arekpalinski — APPROVED** [review]

**Pull request merged**
