### PR TITLE
RavenDB-RemoveNewDatabaseBtn Remove 'new database button'

### PR DESCRIPTION
**Pull request by Danielle9897**

### CODE REVIEW

**Comment by ml054** [comment]
Please don't merge this, we want to remove this butotn from left menu and move to view.

**Comment by gregolsky** [comment]
@ayende We are removing New* actions from menu since it's out of sight, when interacting with the view. They will all go to views as buttons instead of "Add/New something" menu actions.

**Comment by ayende** [comment]
We need this soonest, we are trying to get a version freeze so we can burn the SD cards

**Comment by Danielle9897** [comment]
Closed this PR as requested by @ml054

**Pull request closed without merging**
