### PR TITLE
RavenDB-12506 PageLocator should throw on negative page numbers. In p…

### PR DESCRIPTION
**Pull request by arekpalinski**
…articular the issue was that it returned invalid page for -1 without any error as we initialize by -1 page numbers of pages in cache. That resulted in AVE occasionally.

### CODE REVIEW

**Comment by arekpalinski** [comment]
@redknightlois  Please check http://issues.hibernatingrhinos.com/issue/RavenDB-12506 first for details.

The issue was for a page with number `-1` although I've added a check for any number < 0 to throw early on invalid page number.

**Comment by redknightlois** [comment]
Page Locator is very performance sensitive. I would avoid to add the check if possible. Moreover this issue happens because EOOM as I have been saying all along. We have to get rid of it. @ayende

**Comment by arekpalinski** [comment]
@redknightlois Can you suggest where we could move that check? What I'm trying to achieve is to avoid the page locator to return me an invalid page if I pass `-1` as the requested page number? I can move it to:

https://github.com/ravendb/ravendb/blob/077d74a1a0c0f412444a89d3cf383a662da3f3d2/src/Voron/Impl/LowLevelTransaction.cs#L440-L449

but that would be the same thing effectively, woundn't it?

Indeed, I forced EOOM to cause that but we could arrive here if we get any exception during db creation  (`StorageEnvironment.CreateNewDatabase`), it could also be due to end of disk error I think.

**Comment by redknightlois** [comment]
The proper location for it would be `.GetPageInternal()`, because `PageLocator` is a cache, you should fail only when you are going to get those.

**Comment by redknightlois** [comment]
@ppekrol Revert this one. Let @arekpalinski put the check in the proper place.

**Comment by ppekrol** [comment]
I've wrote to him, he will address this tomorrow morning. It is not like this check is invalid. It just could be placed better.

**Comment by arekpalinski** [comment]
@redknightlois that won't work because `_pageLocator.TryGetReadOnlyPage` is called _before_ `GetPageInternal` and for -1 it will return true and serve invalid page from the cache- that's the issue

**Comment by redknightlois** [comment]
How is that even possible? If it is serving -1 is because someone put it in there.

**Comment by arekpalinski** [comment]
That's because we initialize the cache items by -1:
https://github.com/ravendb/ravendb/blob/6bc40582e401244fa09c67c40406f3bd16290f72/src/Voron/PageLocator.cs#L63

**Comment by redknightlois** [comment]
OK. I just noted that is a TryXXX method... don't throw on TRY... return `false`. 

EDIT: Throwing there have ripple effects on the inlining and code block layout. Returning 'false' does not impact anything.

**Comment by arekpalinski** [comment]
Good point. I'll change it to return false if the page that is going to be returned is invalid (PageNumber == Invalid)

**Comment by arekpalinski** [comment]
I've created: https://github.com/ravendb/ravendb/pull/8255

**Pull request merged**
