### PR TITLE
Raven db 11109 v4.1

### PR DESCRIPTION
**Pull request by talweiss1982**

### CODE REVIEW

**Comment by ml054** [comment]
what about bumping skip count?

**Comment by talweiss1982** [comment]
@ml054 returning null document bumps the error count which is what i believe we want.

**Comment by ml054** [comment]
that's great! I just wanted to verify that.

**Comment by ayende** [comment]
@ml054 We _can_ cancel import, by throwing an error out.
And we need to decide when to actually abort

**Comment by ml054** [comment]
Since we expose import stats, then maybe user should decide to stop import in studio, once he spot too many unexpected errors? auto abort on 20% might not be good for everyone.

**Comment by ayende** [comment]
Okay, good point, given that the user is likely watching this, they can abort as they want

**Pull request merged**
