### PR TITLE
RavenDB-12687: Fix test exception type assertion

### PR DESCRIPTION
**Pull request by aviviadi**

### CODE REVIEW

**Comment by ppekrol** [comment]
@aviviadi do we need to apply it to v4.1 (or even v4.0) ?

**Comment by aviviadi** [comment]
> @aviviadi do we need to apply it to v4.1 (or even v4.0) ?

I haven't seen this test/file in v4.1

**Comment by ppekrol** [comment]
It's there, I think we need to apply it there and then do 4.1 to 4.2 merge.
https://github.com/ravendb/ravendb/blob/v4.0/test/SlowTests/Issues/RavenDB-11836.cs#L37
https://github.com/ravendb/ravendb/blob/v4.1/test/SlowTests/Issues/RavenDB-11836.cs#L37

**Comment by aviviadi** [comment]
> It's there, I think we need to apply it there and then do 4.1 to 4.2 merge.
> https://github.com/ravendb/ravendb/blob/v4.0/test/SlowTests/Issues/RavenDB-11836.cs#L37
> https://github.com/ravendb/ravendb/blob/v4.1/test/SlowTests/Issues/RavenDB-11836.cs#L37

merge to 4.1, 4.0 is underway

**Comment by ppekrol** [comment]
Closing this one down, we will do a 4.1 to 4.2 merge.

**Pull request closed without merging**
