### PR TITLE
RavenDB-15032 Add compare exchange index to sample data

### PR DESCRIPTION
**Pull request by haludi**
https://issues.hibernatingrhinos.com/issue/RavenDB-15032

I added compare exchange per product {key: productId, value: UnitOnStack}
And I created an index by this code
```
private class Products_ByUnitOnStock : AbstractIndexCreationTask<Product>
{
    public class Result
    {
        public int UnitOnStock;
    }

    public Products_ByUnitOnStock()
    {
        Map = employees =>
            from employee in employees
            select new Result {UnitOnStock = LoadCompareExchangeValue<int>(employee.Id)};
    }
}
```

### CODE REVIEW

**Comment by ayende** [comment]
`            from employee in employees` ??

Didn't you mean products?

**Comment by haludi** [comment]
> ` from employee in employees` ??
> 
> Didn't you mean products?

The actual index as shown in the studio is:
```
from product in docs.Products
select new {
    UnitOnStock = LoadCompareExchangeValue(Id(product))
}
```

**Review by ppekrol — APPROVED** [review]

**Review by ayende — APPROVED** [review]

**Comment by haludi** [comment]
Is it worth changing the documentation to address this example for compare exchange and index with a compare exchange?

**Comment by ayende** [comment]
yes

**Comment by ppekrol** [comment]
> Is it worth changing the documentation to address this example for compare exchange and index with a compare exchange?

Create an issue in RDoc and assign to Reeb

**Pull request merged**
