### PR TITLE
RavenDB-13767 when patching cluster transaction documents need to rem…

### PR DESCRIPTION
**Pull request by talweiss1982**
…ove cluster transaction flag (since it was generated from the patch)

### CODE REVIEW

**Review by ayende — APPROVED** [review]

**Review by ppekrol — APPROVED** [review]

**Comment by talweiss1982** [comment]
This is actually breaking changes

**Comment by talweiss1982** [comment]
I can't throw this new exception it mask client expected exception like concurrency exception

**Comment by talweiss1982** [comment]
I didn't see you pushed a commit there @ppekrol, was wondering why my fix failed to push I guess we did it around the same time

**Comment by ppekrol** [comment]
No problem!

**Pull request merged**
