### PR TITLE
	RavenDB-7934 Remove concept of system documents

### PR DESCRIPTION
**Pull request by fitzchak**
I did not run the tests yet

### CODE REVIEW

**Review by ml054 — CHANGES_REQUESTED** [review]
It has at least issues on documents page: isSystemDocuments

**Comment by fitzchak** [comment]
I'll fix the HTML usages, as I didn't removed them

**Comment by ml054** [comment]
Message: Unable to process binding "with: function (){return $root.collectionsTracker.getSystemDocumentsCollection() }"
Message: $root.collectionsTracker.getSystemDocumentsCollection is not a function
    at with (eval at createBindingsStringEvaluator (knockout.debug.js:2992), <anonymous>:3:89)
    at ko.computed.disposeWhenNodeIsRemoved (knockout.debug.js:4391)
    at Function.evaluateImmediate_CallReadThenEndDependencyDetection (knockout.debug.js:2183)
    at Function.evaluateImmediate_CallReadWithDependencyDetection (knockout.debug.js:2150)
    at Function.evaluateImmediate (knockout.debug.js:2111)
    at Object.ko.computed.ko.dependentObservable (knockout.debug.js:1964)
    at init (knockout.debug.js:4390)
    at knockout.debug.js:3368
    at Object.ignore (knockout.debug.js:1480)
    at knockout.debug.js:3367
sys.error @ shell.ts:168

**Comment by fitzchak** [comment]
Fixed: https://github.com/ravendb/ravendb/pull/3620

**Pull request merged**
